vim.cmd("highlight clear")
vim.o.background = "dark"

vim.g.colors_name = "charmtone"
vim.o.termguicolors = true

local p = {
  cumin = "#BF976F",
  tang = "#FF985A",
  yam = "#FFB587",
  bengal = "#FF6E63",
  uni = "#FF937D",
  sriracha = "#EB4268",
  coral = "#FF577D",
  salmon = "#FF7F90",
  cherry = "#FF388B",
  tuna = "#FF6DAA",
  pony = "#FF4FBF",
  cheeky = "#FF79D0",
  dolly = "#FF60FF",
  blush = "#FF84FF",
  crystal = "#EB5DFF",
  lilac = "#F379FF",
  mauve = "#D46EFF",
  orchid = "#AD6EFF",
  charple = "#6B50FF",
  hazy = "#8B75FF",
  larple = "#7B62FF",
  darple = "#5B40EC",
  sapphire = "#4949FF",
  guppy = "#7272FF",
  anchovy = "#719AFC",
  malibu = "#00A4FF",
  sardine = "#4FBEFE",
  turtle = "#0ADCD9",
  lichen = "#5CDFEA",
  julep = "#00FFB2",
  bok = "#68FFD6",
  citron = "#E8FF27",
  zest = "#E8FE96",
  caviar = "#121117",
  bbq = "#2D2C36",
  pepper = "#201F26",
  charcoal = "#3A3943",
  iron = "#4D4C57",
  oyster = "#605F6B",
  squid = "#858392",
  steam = "#A2A0AD",
  smoke = "#BFBCC8",
  ash = "#DFDBDD",
  steep = "#D6D3DC",
  sash = "#ECEBF0",
  salt = "#F1EFEF",
  butter = "#FFFAF1",
  soda = "#FBFBFB",
  none = "NONE",
}

local hl = vim.api.nvim_set_hl

hl(0, "ColorColumn", { bg = p.bbq })
hl(0, "CursorLine", { bg = p.pepper })
hl(0, "CursorColumn", { bg = p.pepper })
hl(0, "CursorLineNr", { fg = p.squid })
hl(0, "Folded", { fg = p.squid, bg = p.bbq })
hl(0, "FoldColumn", { fg = p.iron })
hl(0, "LineNr", { fg = p.iron })
hl(0, "NonText", { fg = p.iron })
hl(0, "Normal", { fg = p.sash, bg = p.bbq })
hl(0, "Pmenu", { fg = p.smoke, bg = p.charcoal })
hl(0, "PmenuSel", { fg = p.ash, bg = p.charple })
hl(0, "PmenuSbar", { bg = p.charcoal })
hl(0, "PmenuThumb", { bg = p.steam })
hl(0, "PmenuKind", { fg = p.lichen, bg = p.charcoal })
hl(0, "PmenuKindSel", { fg = p.ash, bg = p.charple })
hl(0, "PmenuExtra", { fg = p.squid, bg = p.charcoal })
hl(0, "PmenuExtraSel", { fg = p.salt, bg = p.charple })
hl(0, "Search", { fg = p.charcoal, bg = p.zest })
hl(0, "IncSearch", { fg = p.bbq, bg = p.bok, bold = true })
hl(0, "CurSearch", { fg = p.bbq, bg = p.yam, bold = true })
hl(0, "Substitute", { fg = p.bbq, bg = p.salmon })
hl(0, "SignColumn", {})
hl(0, "TabLine", { fg = p.squid, bg = p.pepper })
hl(0, "TabLineFill", { bg = p.pepper })
hl(0, "TabLineSel", { fg = p.smoke, bg = p.bbq })
hl(0, "Title", { fg = p.larple, bold = true })
hl(0, "Visual", { bg = p.charcoal })
hl(0, "WinSeparator", { fg = p.charcoal })
hl(0, "VertSplit", { fg = p.charcoal })
hl(0, "StatusLine", { fg = p.charple, bg = p.pepper })
hl(0, "StatusLineNC", { fg = p.squid, bg = p.bbq })
hl(0, "MsgArea", { fg = p.smoke, bg = p.bbq })
hl(0, "MsgSeparator", { fg = p.charcoal, bg = p.bbq })
hl(0, "ModeMsg", { fg = p.bok })
hl(0, "MoreMsg", { fg = p.lichen })
hl(0, "WarningMsg", { fg = p.zest })
hl(0, "ErrorMsg", { fg = p.salt, bg = p.salmon })
hl(0, "Question", { fg = p.bok, bold = true })
hl(0, "Directory", { fg = p.sardine })
hl(0, "WildMenu", { fg = p.ash, bg = p.charple })
hl(0, "MatchParen", { fg = p.bok, bold = true, underline = true })
hl(0, "QuickFixLine", { fg = p.sash, bg = p.charcoal, bold = true })
hl(0, "WinBar", { fg = p.larple, bg = p.bbq, bold = true })
hl(0, "WinBarNC", { fg = p.squid, bg = p.bbq })
hl(0, "FloatBorder", { fg = p.hazy, bg = p.bbq })
hl(0, "NormalFloat", { fg = p.smoke, bg = p.bbq })
hl(0, "FloatTitle", { fg = p.butter, bg = p.charple, bold = true })
hl(0, "EndOfBuffer", { fg = p.iron })
hl(0, "Conceal", { fg = p.squid })
hl(0, "SpecialKey", { fg = p.iron })
hl(0, "Cursor", { fg = p.bbq, bg = p.sash })
hl(0, "TermCursor", { fg = p.bbq, bg = p.sash })
hl(0, "TermCursorNC", { fg = p.bbq, bg = p.squid })
hl(0, "SpellBad", { undercurl = true, sp = p.salmon })
hl(0, "SpellCap", { undercurl = true, sp = p.zest })
hl(0, "SpellLocal", { undercurl = true, sp = p.sardine })
hl(0, "SpellRare", { undercurl = true, sp = p.lilac })
vim.g.terminal_color_0 = p.pepper
vim.g.terminal_color_1 = p.salmon
vim.g.terminal_color_2 = p.bok
vim.g.terminal_color_3 = p.zest
vim.g.terminal_color_4 = p.charple
vim.g.terminal_color_5 = p.dolly
vim.g.terminal_color_6 = p.sardine
vim.g.terminal_color_7 = p.smoke
vim.g.terminal_color_8 = p.iron
vim.g.terminal_color_9 = p.tuna
vim.g.terminal_color_10 = p.julep
vim.g.terminal_color_11 = p.zest
vim.g.terminal_color_12 = p.guppy
vim.g.terminal_color_13 = p.blush
vim.g.terminal_color_14 = p.lichen
vim.g.terminal_color_15 = p.salt
hl(0, "Comment", { fg = p.oyster })
hl(0, "Constant", { fg = p.bok })
hl(0, "String", { fg = p.yam })
hl(0, "Character", { fg = p.bok })
hl(0, "Number", { fg = p.bok })
hl(0, "Boolean", { fg = p.sardine, bold = true })
hl(0, "Float", { fg = p.bok })
hl(0, "Identifier", { fg = p.steep })
hl(0, "Function", { fg = p.sardine })
hl(0, "Statement", { fg = p.guppy })
hl(0, "Conditional", { fg = p.pony })
hl(0, "Repeat", { fg = p.pony })
hl(0, "Label", { fg = p.cheeky })
hl(0, "Operator", { fg = p.salmon })
hl(0, "Keyword", { fg = p.guppy })
hl(0, "Exception", { fg = p.tuna })
hl(0, "PreProc", { fg = p.uni })
hl(0, "Include", { fg = p.cheeky })
hl(0, "Define", { fg = p.uni })
hl(0, "Macro", { fg = p.lichen })
hl(0, "PreCondit", { fg = p.uni })
hl(0, "Type", { fg = p.salt })
hl(0, "StorageClass", { fg = p.guppy })
hl(0, "Structure", { fg = p.salt })
hl(0, "Typedef", { fg = p.salt })
hl(0, "Special", { fg = p.bok })
hl(0, "SpecialChar", { fg = p.bok })
hl(0, "Tag", { fg = p.orchid })
hl(0, "Delimiter", { fg = p.zest })
hl(0, "SpecialComment", { fg = p.oyster })
hl(0, "Debug", { fg = p.sardine })
hl(0, "Todo", { fg = p.zest, bold = true })
hl(0, "Error", { fg = p.salt, bg = p.salmon })
hl(0, "Underlined", { underline = true })
hl(0, "Ignore", { fg = p.oyster })
hl(0, "@variable", { fg = p.sash })
hl(0, "@variable.builtin", { fg = p.cheeky })
hl(0, "@variable.parameter", { fg = p.yam })
hl(0, "@variable.parameter.builtin", { fg = p.yam })
hl(0, "@variable.member", { fg = p.guppy })
hl(0, "@constant", { fg = p.bok })
hl(0, "@constant.builtin", { fg = p.bok, bold = true })
hl(0, "@constant.macro", { fg = p.lichen })
hl(0, "@module", { fg = p.salmon })
hl(0, "@module.builtin", { fg = p.cheeky })
hl(0, "@label", { fg = p.cheeky })
hl(0, "@string", { fg = p.yam })
hl(0, "@string.documentation", { fg = p.oyster, italic = true })
hl(0, "@string.regexp", { fg = p.lichen })
hl(0, "@string.escape", { fg = p.bok })
hl(0, "@string.special", { fg = p.zest })
hl(0, "@string.special.symbol", { fg = p.lichen })
hl(0, "@string.special.url", { fg = p.sardine, underline = true })
hl(0, "@string.special.path", { fg = p.yam })
hl(0, "@character", { fg = p.yam })
hl(0, "@character.special", { fg = p.bok })
hl(0, "@boolean", { fg = p.sardine, bold = true })
hl(0, "@number", { fg = p.bok })
hl(0, "@number.float", { fg = p.bok })
hl(0, "@type", { fg = p.salt })
hl(0, "@type.builtin", { fg = p.guppy })
hl(0, "@type.definition", { fg = p.salt })
hl(0, "@attribute", { fg = p.guppy })
hl(0, "@attribute.builtin", { fg = p.guppy })
hl(0, "@property", { fg = p.guppy })
hl(0, "@function", { fg = p.sardine })
hl(0, "@function.builtin", { fg = p.cheeky })
hl(0, "@function.call", { fg = p.sardine })
hl(0, "@function.macro", { fg = p.lichen })
hl(0, "@function.method", { fg = p.anchovy })
hl(0, "@function.method.call", { fg = p.anchovy })
hl(0, "@constructor", { fg = p.salt })
hl(0, "@operator", { fg = p.salmon })
hl(0, "@keyword", { fg = p.guppy })
hl(0, "@keyword.coroutine", { fg = p.guppy })
hl(0, "@keyword.function", { fg = p.guppy })
hl(0, "@keyword.operator", { fg = p.salmon })
hl(0, "@keyword.import", { fg = p.cheeky })
hl(0, "@keyword.type", { fg = p.guppy })
hl(0, "@keyword.modifier", { fg = p.guppy })
hl(0, "@keyword.repeat", { fg = p.pony })
hl(0, "@keyword.return", { fg = p.pony })
hl(0, "@keyword.debug", { fg = p.guppy })
hl(0, "@keyword.exception", { fg = p.tuna })
hl(0, "@keyword.conditional", { fg = p.pony })
hl(0, "@keyword.conditional.ternary", { fg = p.pony })
hl(0, "@keyword.directive", { fg = p.uni })
hl(0, "@keyword.directive.define", { fg = p.uni })
hl(0, "@punctuation.delimiter", { fg = p.zest })
hl(0, "@punctuation.bracket", { fg = p.zest })
hl(0, "@punctuation.special", { fg = p.zest })
hl(0, "@comment", { fg = p.oyster })
hl(0, "@comment.documentation", { fg = p.oyster })
hl(0, "@comment.error", { fg = p.tuna })
hl(0, "@comment.warning", { fg = p.zest })
hl(0, "@comment.todo", { fg = p.squid })
hl(0, "@comment.note", { fg = p.sardine })
hl(0, "@diff.plus", { fg = p.bok })
hl(0, "@diff.minus", { fg = p.salmon })
hl(0, "@diff.delta", { fg = p.squid })
hl(0, "@tag", { fg = p.orchid })
hl(0, "@tag.builtin", { fg = p.orchid })
hl(0, "@tag.attribute", { fg = p.guppy })
hl(0, "@tag.delimiter", { fg = p.zest })
hl(0, "@markup.heading", { fg = p.dolly, bold = true })
hl(0, "@markup.heading.1", { fg = p.dolly, bold = true })
hl(0, "@markup.heading.2", { fg = p.guppy, bold = true })
hl(0, "@markup.heading.3", { fg = p.lichen, bold = true })
hl(0, "@markup.heading.4", { fg = p.bok, bold = true })
hl(0, "@markup.heading.5", { fg = p.zest, bold = true })
hl(0, "@markup.heading.6", { fg = p.yam, bold = true })
hl(0, "@markup.quote", { fg = p.oyster, italic = true })
hl(0, "@markup.math", { fg = p.yam })
hl(0, "@markup.link", { fg = p.sardine, underline = true })
hl(0, "@markup.link.label", { fg = p.cheeky })
hl(0, "@markup.link.url", { fg = p.sardine, underline = true })
hl(0, "@markup.raw", { fg = p.bok })
hl(0, "@markup.raw.block", { fg = p.bok })
hl(0, "@markup.list", { fg = p.dolly })
hl(0, "@markup.list.checked", { fg = p.bok })
hl(0, "@markup.list.unchecked", { fg = p.squid })
hl(0, "DiagnosticError", { fg = p.salmon })
hl(0, "DiagnosticWarn", { fg = p.zest })
hl(0, "DiagnosticInfo", { fg = p.sardine })
hl(0, "DiagnosticHint", { fg = p.squid })
hl(0, "DiagnosticOk", { fg = p.bok })
hl(0, "DiagnosticUnderlineError", { undercurl = true, sp = p.salmon })
hl(0, "DiagnosticUnderlineWarn", { undercurl = true, sp = p.zest })
hl(0, "DiagnosticUnderlineInfo", { undercurl = true, sp = p.sardine })
hl(0, "DiagnosticUnderlineHint", { undercurl = true, sp = p.squid })
hl(0, "DiagnosticUnderlineOk", { undercurl = true, sp = p.bok })
hl(0, "DiagnosticVirtualTextError", { fg = p.salmon })
hl(0, "DiagnosticVirtualTextWarn", { fg = p.zest })
hl(0, "DiagnosticVirtualTextInfo", { fg = p.sardine })
hl(0, "DiagnosticVirtualTextHint", { fg = p.squid })
hl(0, "DiagnosticVirtualTextOk", { fg = p.bok })
hl(0, "DiagnosticFloatingError", { fg = p.salmon, bg = p.bbq })
hl(0, "DiagnosticFloatingWarn", { fg = p.zest, bg = p.bbq })
hl(0, "DiagnosticFloatingInfo", { fg = p.sardine, bg = p.bbq })
hl(0, "DiagnosticFloatingHint", { fg = p.squid, bg = p.bbq })
hl(0, "DiagnosticFloatingOk", { fg = p.bok, bg = p.bbq })
hl(0, "DiagnosticSignError", { fg = p.salmon })
hl(0, "DiagnosticSignWarn", { fg = p.zest })
hl(0, "DiagnosticSignInfo", { fg = p.sardine })
hl(0, "DiagnosticSignHint", { fg = p.squid })
hl(0, "DiagnosticSignOk", { fg = p.bok })
hl(0, "DiffAdd", { fg = p.bok, bg = p.pepper })
hl(0, "DiffChange", { fg = p.yam, bg = p.pepper })
hl(0, "DiffDelete", { fg = p.salmon, bg = p.pepper })
hl(0, "DiffText", { fg = p.salt, bg = p.guppy, bold = true })
hl(0, "diffAdded", { fg = p.bok })
hl(0, "diffRemoved", { fg = p.salmon })
hl(0, "diffChanged", { fg = p.yam })
hl(0, "diffOldFile", { fg = p.tuna })
hl(0, "diffNewFile", { fg = p.bok })
hl(0, "diffFile", { fg = p.sardine })
hl(0, "diffLine", { fg = p.squid })
hl(0, "diffIndexLine", { fg = p.lilac })
hl(0, "GitGutterAdd", { fg = p.bok })
hl(0, "GitGutterChange", { fg = p.yam })
hl(0, "GitGutterDelete", { fg = p.salmon })
hl(0, "GitSignsAdd", { fg = p.bok })
hl(0, "GitSignsChange", { fg = p.yam })
hl(0, "GitSignsDelete", { fg = p.salmon })
hl(0, "GitSignsAddNr", { fg = p.bok })
hl(0, "GitSignsChangeNr", { fg = p.yam })
hl(0, "GitSignsDeleteNr", { fg = p.salmon })
hl(0, "GitSignsAddLn", { fg = p.bok, bg = p.pepper })
hl(0, "GitSignsChangeLn", { fg = p.yam, bg = p.pepper })
hl(0, "GitSignsDeleteLn", { fg = p.salmon, bg = p.pepper })
hl(0, "GitSignsAddInline", { fg = p.bok, bg = p.charcoal })
hl(0, "GitSignsChangeInline", { fg = p.yam, bg = p.charcoal })
hl(0, "GitSignsDeleteInline", { fg = p.salmon, bg = p.charcoal })
hl(0, "GitSignsAddVirtLn", { fg = p.bok, bg = p.pepper })
hl(0, "GitSignsDeleteVirtLn", { fg = p.salmon, bg = p.pepper })
hl(0, "GitSignsCurrentLineBlame", { fg = p.squid, italic = true })
hl(0, "GitSignsAddPreview", { fg = p.bok })
hl(0, "GitSignsDeletePreview", { fg = p.salmon })
hl(0, "LazyNormal", { fg = p.smoke, bg = p.bbq })
hl(0, "LazyH1", { fg = p.butter, bg = p.charple, bold = true })
hl(0, "LazyH2", { fg = p.larple, bold = true })
hl(0, "LazyButton", { fg = p.squid, bg = p.pepper })
hl(0, "LazyButtonActive", { fg = p.ash, bg = p.charple })
hl(0, "LazyComment", { fg = p.squid, italic = true })
hl(0, "LazyCommit", { fg = p.bok })
hl(0, "LazyCommitIssue", { fg = p.tuna })
hl(0, "LazyCommitType", { fg = p.blush })
hl(0, "LazyCommitScope", { fg = p.sardine })
hl(0, "LazyDimmed", { fg = p.squid })
hl(0, "LazyDir", { fg = p.anchovy })
hl(0, "LazyLocal", { fg = p.lichen })
hl(0, "LazyProp", { fg = p.guppy })
hl(0, "LazyReasonCmd", { fg = p.zest })
hl(0, "LazyReasonEvent", { fg = p.tuna })
hl(0, "LazyReasonFt", { fg = p.blush })
hl(0, "LazyReasonImport", { fg = p.sardine })
hl(0, "LazyReasonKeys", { fg = p.anchovy })
hl(0, "LazyReasonPlugin", { fg = p.bok })
hl(0, "LazyReasonRuntime", { fg = p.hazy })
hl(0, "LazyReasonSource", { fg = p.lichen })
hl(0, "LazyReasonStart", { fg = p.julep })
hl(0, "LazySpecial", { fg = p.lichen })
hl(0, "LazyTaskError", { fg = p.salmon })
hl(0, "LazyTaskOutput", { fg = p.smoke })
hl(0, "LazyUrl", { fg = p.sardine, underline = true })
hl(0, "LazyValue", { fg = p.bok })
hl(0, "MasonNormal", { fg = p.smoke, bg = p.bbq })
hl(0, "MasonHeader", { fg = p.butter, bg = p.charple, bold = true })
hl(0, "MasonHeaderSecondary", { fg = p.bbq, bg = p.bok, bold = true })
hl(0, "MasonHighlight", { fg = p.sardine })
hl(0, "MasonHighlightBlock", { fg = p.ash, bg = p.charple })
hl(0, "MasonHighlightBlockBold", { fg = p.ash, bg = p.charple, bold = true })
hl(0, "MasonHighlightSecondary", { fg = p.lichen })
hl(0, "MasonHighlightBlockSecondary", { fg = p.bbq, bg = p.lichen })
hl(0, "MasonHighlightBlockBoldSecondary", { fg = p.bbq, bg = p.lichen, bold = true })
hl(0, "MasonMuted", { fg = p.squid })
hl(0, "MasonMutedBlock", { fg = p.squid, bg = p.pepper })
hl(0, "MasonMutedBlockBold", { fg = p.smoke, bg = p.pepper, bold = true })
hl(0, "MasonError", { fg = p.salmon })
hl(0, "MasonWarning", { fg = p.zest })
hl(0, "MasonHeading", { fg = p.larple, bold = true })
hl(0, "TelescopeNormal", { fg = p.smoke, bg = p.bbq })
hl(0, "TelescopeBorder", { fg = p.charcoal, bg = p.bbq })
hl(0, "TelescopeTitle", { fg = p.butter, bg = p.charple, bold = true })
hl(0, "TelescopePromptNormal", { fg = p.smoke, bg = p.charcoal })
hl(0, "TelescopePromptBorder", { fg = p.charcoal, bg = p.charcoal })
hl(0, "TelescopePromptTitle", { fg = p.butter, bg = p.charple, bold = true })
hl(0, "TelescopePromptPrefix", { fg = p.sardine, bg = p.charcoal })
hl(0, "TelescopePromptCounter", { fg = p.squid, bg = p.charcoal })
hl(0, "TelescopePreviewNormal", { fg = p.smoke, bg = p.bbq })
hl(0, "TelescopePreviewBorder", { fg = p.bbq, bg = p.bbq })
hl(0, "TelescopePreviewTitle", { fg = p.bbq, bg = p.bok, bold = true })
hl(0, "TelescopeResultsNormal", { fg = p.smoke, bg = p.bbq })
hl(0, "TelescopeResultsBorder", { fg = p.bbq, bg = p.bbq })
hl(0, "TelescopeResultsTitle", { fg = p.bbq, bg = p.sardine, bold = true })
hl(0, "TelescopeSelection", { fg = p.ash, bg = p.charcoal })
hl(0, "TelescopeSelectionCaret", { fg = p.dolly, bg = p.charcoal })
hl(0, "TelescopeMultiSelection", { fg = p.lichen, bg = p.charcoal })
hl(0, "TelescopeMatching", { fg = p.bok, bold = true })
hl(0, "TelescopePreviewLine", { bg = p.charcoal })
hl(0, "TelescopePreviewMatch", { fg = p.ash, bg = p.charple })
hl(0, "BufferLineBackground", { bg = p.pepper })
hl(0, "BufferLineBuffer", { fg = p.smoke, bg = p.pepper })
hl(0, "BufferLineBufferVisible", { fg = p.smoke, bg = p.pepper })
hl(0, "BufferLineBufferSelected", { fg = p.sash, bg = p.bbq })
hl(0, "BufferLineCurrent", { fg = p.sash, bg = p.bbq, bold = true })
hl(0, "BufferLineVisible", { fg = p.smoke, bg = p.pepper })
hl(0, "BufferLineInactive", { fg = p.squid, bg = p.pepper })
hl(0, "BufferLineInactiveVisible", { fg = p.smoke, bg = p.pepper })
hl(0, "BufferLineIndicatorSelected", { fg = p.larple, bg = p.bbq })
hl(0, "BufferLineIndicatorVisible", { fg = p.iron, bg = p.pepper })
hl(0, "BufferLineIndicatorInactive", { fg = p.iron, bg = p.pepper })
hl(0, "BufferLineModified", { fg = p.yam, bg = p.pepper })
hl(0, "BufferLineModifiedVisible", { fg = p.yam, bg = p.pepper })
hl(0, "BufferLineModifiedCurrent", { fg = p.yam, bg = p.bbq })
hl(0, "BufferLineError", { fg = p.salmon, bg = p.pepper })
hl(0, "BufferLineErrorVisible", { fg = p.salmon, bg = p.pepper })
hl(0, "BufferLineErrorDiagnostic", { fg = p.salmon, bg = p.pepper })
hl(0, "BufferLineErrorDiagnosticVisible", { fg = p.salmon, bg = p.pepper })
hl(0, "BufferLineWarning", { fg = p.zest, bg = p.pepper })
hl(0, "BufferLineWarningDiagnostic", { fg = p.zest, bg = p.pepper })
hl(0, "BufferLineCloseButton", { fg = p.squid, bg = p.pepper })
hl(0, "BufferLineCloseButtonVisible", { fg = p.smoke, bg = p.pepper })
hl(0, "BufferLineCloseButtonSelected", { fg = p.sash, bg = p.bbq })
hl(0, "BufferLineDuplicate", { fg = p.squid, bg = p.pepper, italic = true })
hl(0, "BufferLineDuplicateSelected", { fg = p.squid, bg = p.bbq, italic = true })
hl(0, "BufferLineDuplicateVisible", { fg = p.squid, bg = p.pepper, italic = true })
hl(0, "BufferLineNumbers", { fg = p.squid, bg = p.pepper })
hl(0, "BufferLineNumbersSelected", { fg = p.sash, bg = p.bbq, bold = true })
hl(0, "BufferLineNumbersVisible", { fg = p.smoke, bg = p.pepper })
hl(0, "BufferLineDiagnosticError", { fg = p.salmon, bg = p.pepper })
hl(0, "BufferLineDiagnosticWarning", { fg = p.zest, bg = p.pepper })
hl(0, "BufferLineDiagnosticInfo", { fg = p.sardine, bg = p.pepper })
hl(0, "BufferLineDiagnosticHint", { fg = p.squid, bg = p.pepper })
hl(0, "BufferLineTabSelected", { fg = p.ash, bg = p.charple })
hl(0, "BufferLineTab", { fg = p.squid, bg = p.pepper })
hl(0, "BufferLineTabClose", { fg = p.squid, bg = p.pepper })
hl(0, "BufferLineOffset", { fg = p.smoke, bg = p.charcoal })
hl(0, "NeoTreeNormal", { fg = p.smoke, bg = p.pepper })
hl(0, "NeoTreeNormalNC", { fg = p.smoke, bg = p.pepper })
hl(0, "NeoTreeWinSeparator", { fg = p.pepper, bg = p.pepper })
hl(0, "NeoTreeEndOfBuffer", { fg = p.pepper, bg = p.pepper })
hl(0, "NeoTreeRootName", { fg = p.dolly, bold = true })
hl(0, "NeoTreeDirectoryName", { fg = p.hazy })
hl(0, "NeoTreeDirectoryIcon", { fg = p.hazy })
hl(0, "NeoTreeFileName", { fg = p.ash })
hl(0, "NeoTreeFileIcon", { fg = p.squid })
hl(0, "NeoTreeFileNameOpened", { fg = p.bok, bold = true })
hl(0, "NeoTreeIndentMarker", { fg = p.charcoal })
hl(0, "NeoTreeExpander", { fg = p.iron })
hl(0, "NeoTreeSymbolicLinkTarget", { fg = p.lichen })
hl(0, "NeoTreeGitAdded", { fg = p.bok })
hl(0, "NeoTreeGitConflict", { fg = p.salmon, bold = true })
hl(0, "NeoTreeGitDeleted", { fg = p.tuna })
hl(0, "NeoTreeGitIgnored", { fg = p.squid, italic = true })
hl(0, "NeoTreeGitModified", { fg = p.yam })
hl(0, "NeoTreeGitUnstaged", { fg = p.yam })
hl(0, "NeoTreeGitUntracked", { fg = p.bok })
hl(0, "NeoTreeGitStaged", { fg = p.bok })
hl(0, "NeoTreeFloatBorder", { fg = p.hazy, bg = p.bbq })
hl(0, "NeoTreeFloatTitle", { fg = p.butter, bg = p.charple, bold = true })
hl(0, "NeoTreeTitleBar", { fg = p.butter, bg = p.charple, bold = true })
hl(0, "NeoTreeCursorLine", { bg = p.charcoal })
hl(0, "NeoTreeDimText", { fg = p.iron })
hl(0, "NeoTreeFilterTerm", { fg = p.bok, bold = true })
hl(0, "NeoTreeTabActive", { fg = p.smoke, bg = p.bbq, bold = true })
hl(0, "NeoTreeTabInactive", { fg = p.squid, bg = p.pepper })
hl(0, "NeoTreeTabSeparatorActive", { fg = p.bbq, bg = p.bbq })
hl(0, "NeoTreeTabSeparatorInactive", { fg = p.pepper, bg = p.pepper })
hl(0, "NvimTreeNormal", { fg = p.smoke, bg = p.pepper })
hl(0, "NvimTreeNormalNC", { fg = p.smoke, bg = p.pepper })
hl(0, "NvimTreeWinSeparator", { fg = p.pepper, bg = p.pepper })
hl(0, "NvimTreeRootFolder", { fg = p.dolly, bold = true })
hl(0, "NvimTreeFolderName", { fg = p.hazy })
hl(0, "NvimTreeFolderIcon", { fg = p.hazy })
hl(0, "NvimTreeEmptyFolderName", { fg = p.squid })
hl(0, "NvimTreeOpenedFolderName", { fg = p.bok, bold = true })
hl(0, "NvimTreeIndentMarker", { fg = p.charcoal })
hl(0, "NvimTreeSymlink", { fg = p.lichen })
hl(0, "NvimTreeGitDirty", { fg = p.yam })
hl(0, "NvimTreeGitStaged", { fg = p.bok })
hl(0, "NvimTreeGitMerge", { fg = p.lilac })
hl(0, "NvimTreeGitRenamed", { fg = p.mauve })
hl(0, "NvimTreeGitNew", { fg = p.bok })
hl(0, "NvimTreeGitDeleted", { fg = p.tuna })
hl(0, "NvimTreeGitIgnored", { fg = p.squid, italic = true })
hl(0, "NvimTreeSpecialFile", { fg = p.blush, underline = true })
hl(0, "NvimTreeOpenedHL", { fg = p.bok })
hl(0, "BlinkCmpMenu", { fg = p.smoke, bg = p.charcoal })
hl(0, "BlinkCmpMenuBorder", { fg = p.hazy, bg = p.charcoal })
hl(0, "BlinkCmpMenuSelection", { fg = p.ash, bg = p.charple })
hl(0, "BlinkCmpScrollBarThumb", { bg = p.steam })
hl(0, "BlinkCmpScrollBarGutter", { bg = p.charcoal })
hl(0, "BlinkCmpLabel", { fg = p.smoke })
hl(0, "BlinkCmpLabelMatch", { fg = p.bok, bold = true })
hl(0, "BlinkCmpLabelDeprecated", { fg = p.squid, strikethrough = true })
hl(0, "BlinkCmpLabelDetail", { fg = p.squid })
hl(0, "BlinkCmpLabelDescription", { fg = p.squid })
hl(0, "BlinkCmpSource", { fg = p.squid, italic = true })
hl(0, "BlinkCmpSourceBuffer", { fg = p.squid, italic = true })
hl(0, "BlinkCmpGhostText", { fg = p.oyster })
hl(0, "BlinkCmpDoc", { fg = p.smoke, bg = p.bbq })
hl(0, "BlinkCmpDocBorder", { fg = p.charcoal, bg = p.bbq })
hl(0, "BlinkCmpDocSeparator", { fg = p.charcoal, bg = p.bbq })
hl(0, "BlinkCmpSignatureHelp", { fg = p.smoke, bg = p.charcoal })
hl(0, "BlinkCmpSignatureHelpBorder", { fg = p.hazy, bg = p.charcoal })
hl(0, "BlinkCmpSignatureHelpActiveParameter", { fg = p.yam, bold = true })
hl(0, "BlinkCmpKind", { fg = p.sardine })
hl(0, "BlinkCmpKindText", { fg = p.smoke })
hl(0, "BlinkCmpKindMethod", { fg = p.sardine })
hl(0, "BlinkCmpKindFunction", { fg = p.sardine })
hl(0, "BlinkCmpKindConstructor", { fg = p.salt })
hl(0, "BlinkCmpKindField", { fg = p.guppy })
hl(0, "BlinkCmpKindVariable", { fg = p.sash })
hl(0, "BlinkCmpKindClass", { fg = p.salt })
hl(0, "BlinkCmpKindInterface", { fg = p.salt })
hl(0, "BlinkCmpKindModule", { fg = p.salmon })
hl(0, "BlinkCmpKindProperty", { fg = p.guppy })
hl(0, "BlinkCmpKindUnit", { fg = p.bok })
hl(0, "BlinkCmpKindValue", { fg = p.bok })
hl(0, "BlinkCmpKindEnum", { fg = p.salt })
hl(0, "BlinkCmpKindKeyword", { fg = p.guppy })
hl(0, "BlinkCmpKindSnippet", { fg = p.blush })
hl(0, "BlinkCmpKindColor", { fg = p.blush })
hl(0, "BlinkCmpKindFile", { fg = p.sardine })
hl(0, "BlinkCmpKindReference", { fg = p.lichen })
hl(0, "BlinkCmpKindFolder", { fg = p.anchovy })
hl(0, "BlinkCmpKindEnumMember", { fg = p.bok })
hl(0, "BlinkCmpKindConstant", { fg = p.bok })
hl(0, "BlinkCmpKindStruct", { fg = p.salt })
hl(0, "BlinkCmpKindEvent", { fg = p.tuna })
hl(0, "BlinkCmpKindOperator", { fg = p.salmon })
hl(0, "BlinkCmpKindTypeParameter", { fg = p.guppy })
hl(0, "BlinkCmpKindCopilot", { fg = p.blush })
hl(0, "BlinkCmpKindCodeium", { fg = p.blush })
hl(0, "BlinkCmpKindSupermaven", { fg = p.blush })
hl(0, "BlinkCmpKindTabNine", { fg = p.blush })
hl(0, "CmpNormal", { fg = p.smoke, bg = p.charcoal })
hl(0, "CmpBorder", { fg = p.hazy, bg = p.charcoal })
hl(0, "CmpDocumentation", { fg = p.smoke, bg = p.bbq })
hl(0, "CmpDocumentationBorder", { fg = p.charcoal, bg = p.bbq })
hl(0, "CmpItemAbbr", { fg = p.smoke })
hl(0, "CmpItemAbbrDeprecated", { fg = p.squid, strikethrough = true })
hl(0, "CmpItemAbbrMatch", { fg = p.bok, bold = true })
hl(0, "CmpItemAbbrMatchFuzzy", { fg = p.bok, bold = true })
hl(0, "CmpItemMenu", { fg = p.squid, italic = true })
hl(0, "CmpItemKind", { fg = p.sardine })
hl(0, "CmpItemKindText", { fg = p.smoke })
hl(0, "CmpItemKindMethod", { fg = p.sardine })
hl(0, "CmpItemKindFunction", { fg = p.sardine })
hl(0, "CmpItemKindConstructor", { fg = p.salt })
hl(0, "CmpItemKindField", { fg = p.guppy })
hl(0, "CmpItemKindVariable", { fg = p.sash })
hl(0, "CmpItemKindClass", { fg = p.salt })
hl(0, "CmpItemKindInterface", { fg = p.salt })
hl(0, "CmpItemKindModule", { fg = p.salmon })
hl(0, "CmpItemKindProperty", { fg = p.guppy })
hl(0, "CmpItemKindUnit", { fg = p.bok })
hl(0, "CmpItemKindValue", { fg = p.bok })
hl(0, "CmpItemKindEnum", { fg = p.salt })
hl(0, "CmpItemKindKeyword", { fg = p.guppy })
hl(0, "CmpItemKindSnippet", { fg = p.blush })
hl(0, "CmpItemKindColor", { fg = p.blush })
hl(0, "CmpItemKindFile", { fg = p.sardine })
hl(0, "CmpItemKindReference", { fg = p.lichen })
hl(0, "CmpItemKindFolder", { fg = p.anchovy })
hl(0, "CmpItemKindEnumMember", { fg = p.bok })
hl(0, "CmpItemKindConstant", { fg = p.bok })
hl(0, "CmpItemKindStruct", { fg = p.salt })
hl(0, "CmpItemKindEvent", { fg = p.tuna })
hl(0, "CmpItemKindOperator", { fg = p.salmon })
hl(0, "CmpItemKindTypeParameter", { fg = p.guppy })
hl(0, "CmpItemKindCopilot", { fg = p.blush })
hl(0, "CmpItemKindCodeium", { fg = p.blush })
hl(0, "CmpItemKindTabNine", { fg = p.blush })
hl(0, "CmpItemKindSuperMaven", { fg = p.blush })
hl(0, "NoicePopup", { fg = p.smoke, bg = p.bbq })
hl(0, "NoicePopupBorder", { fg = p.hazy, bg = p.bbq })
hl(0, "NoiceCmdline", { fg = p.smoke, bg = p.charcoal })
hl(0, "NoiceCmdlinePopup", { fg = p.smoke, bg = p.charcoal })
hl(0, "NoiceCmdlinePopupBorder", { fg = p.hazy, bg = p.charcoal })
hl(0, "NoiceCmdlinePopupTitle", { fg = p.butter, bg = p.charple, bold = true })
hl(0, "NoiceCmdlineIcon", { fg = p.sardine })
hl(0, "NoiceCmdlineIconSearch", { fg = p.zest })
hl(0, "NoiceConfirm", { fg = p.smoke, bg = p.bbq })
hl(0, "NoiceConfirmBorder", { fg = p.hazy, bg = p.bbq })
hl(0, "NoiceMini", { fg = p.smoke, bg = p.bbq })
hl(0, "NoiceFormatProgressDone", { fg = p.bbq, bg = p.bok })
hl(0, "NoiceFormatProgressTodo", { fg = p.squid, bg = p.charcoal })
hl(0, "NoiceLspProgressClient", { fg = p.mauve })
hl(0, "NoiceLspProgressSpinner", { fg = p.lichen })
hl(0, "NoiceLspProgressTitle", { fg = p.smoke })
hl(0, "WhichKey", { fg = p.bok, bold = true })
hl(0, "WhichKeyGroup", { fg = p.guppy })
hl(0, "WhichKeyDesc", { fg = p.sash })
hl(0, "WhichKeySeparator", { fg = p.squid })
hl(0, "WhichKeyFloat", { bg = p.bbq })
hl(0, "WhichKeyBorder", { fg = p.charcoal, bg = p.bbq })
hl(0, "WhichKeyValue", { fg = p.squid })
hl(0, "IblIndent", { fg = p.charcoal })
hl(0, "IblWhitespace", { fg = p.charcoal })
hl(0, "IblScope", { fg = p.hazy })
hl(0, "IndentBlanklineChar", { fg = p.charcoal })
hl(0, "IndentBlanklineSpaceChar", { fg = p.charcoal })
hl(0, "IndentBlanklineContextChar", { fg = p.hazy })
hl(0, "IndentBlanklineContextStart", { underline = true, sp = p.hazy })
hl(0, "SnacksIndent", { fg = p.charcoal })
hl(0, "SnacksIndentScope", { fg = p.hazy })
hl(0, "MiniIndentscopeSymbol", { fg = p.hazy })
hl(0, "SnacksDashboardHeader", { fg = p.larple, bold = true })
hl(0, "SnacksDashboardIcon", { fg = p.bok })
hl(0, "SnacksDashboardDesc", { fg = p.smoke })
hl(0, "SnacksDashboardKey", { fg = p.yam, bold = true })
hl(0, "SnacksDashboardFooter", { fg = p.squid, italic = true })
hl(0, "SnacksDashboardSpecial", { fg = p.zest })
hl(0, "SnacksDashboardDir", { fg = p.squid })
hl(0, "SnacksDashboardDirPath", { fg = p.squid })
hl(0, "SnacksDashboardSection", { fg = p.lichen, bold = true })
hl(0, "SnacksDashboardNormal", { fg = p.smoke, bg = p.bbq })
hl(0, "DashboardHeader", { fg = p.larple, bold = true })
hl(0, "DashboardCenter", { fg = p.lichen })
hl(0, "DashboardShortCut", { fg = p.yam })
hl(0, "DashboardFooter", { fg = p.squid, italic = true })
hl(0, "AlphaHeader", { fg = p.larple, bold = true })
hl(0, "AlphaButtons", { fg = p.lichen })
hl(0, "AlphaShortcut", { fg = p.yam, bold = true })
hl(0, "AlphaFooter", { fg = p.squid, italic = true })
hl(0, "NotifyERRORBorder", { fg = p.salmon, bg = p.bbq })
hl(0, "NotifyERRORIcon", { fg = p.salmon })
hl(0, "NotifyERRORTitle", { fg = p.salmon, bold = true })
hl(0, "NotifyERRORBody", { fg = p.smoke, bg = p.bbq })
hl(0, "NotifyWARNBorder", { fg = p.zest, bg = p.bbq })
hl(0, "NotifyWARNIcon", { fg = p.zest })
hl(0, "NotifyWARNTitle", { fg = p.zest, bold = true })
hl(0, "NotifyWARNBody", { fg = p.smoke, bg = p.bbq })
hl(0, "NotifyINFOBorder", { fg = p.sardine, bg = p.bbq })
hl(0, "NotifyINFOIcon", { fg = p.sardine })
hl(0, "NotifyINFOTitle", { fg = p.sardine, bold = true })
hl(0, "NotifyINFOBody", { fg = p.smoke, bg = p.bbq })
hl(0, "NotifyDEBUGBorder", { fg = p.squid, bg = p.bbq })
hl(0, "NotifyDEBUGIcon", { fg = p.squid })
hl(0, "NotifyDEBUGTitle", { fg = p.squid, bold = true })
hl(0, "NotifyDEBUGBody", { fg = p.smoke, bg = p.bbq })
hl(0, "NotifyTRACEBorder", { fg = p.lilac, bg = p.bbq })
hl(0, "NotifyTRACEIcon", { fg = p.lilac })
hl(0, "NotifyTRACETitle", { fg = p.lilac, bold = true })
hl(0, "NotifyTRACEBody", { fg = p.smoke, bg = p.bbq })
hl(0, "NotifyBackground", { bg = p.bbq })
hl(0, "TroubleNormal", { fg = p.smoke, bg = p.bbq })
hl(0, "TroubleText", { fg = p.smoke })
hl(0, "TroubleCount", { fg = p.lilac, bold = true })
hl(0, "TroubleCode", { fg = p.squid })
hl(0, "TroubleDirectory", { fg = p.sardine })
hl(0, "TroubleSource", { fg = p.squid })
hl(0, "TroubleFile", { fg = p.anchovy })
hl(0, "TroubleIndent", { fg = p.iron })
hl(0, "TroubleLocation", { fg = p.squid })
hl(0, "TroubleFoldIcon", { fg = p.lilac })
hl(0, "TroubleTextError", { fg = p.salmon })
hl(0, "TroubleTextWarning", { fg = p.zest })
hl(0, "TroubleTextInformation", { fg = p.sardine })
hl(0, "TroubleTextHint", { fg = p.squid })
hl(0, "TroubleSignError", { fg = p.salmon })
hl(0, "TroubleSignWarning", { fg = p.zest })
hl(0, "TroubleSignInformation", { fg = p.sardine })
hl(0, "TroubleSignHint", { fg = p.squid })
hl(0, "TodoBgFIX", { fg = p.bbq, bg = p.salmon, bold = true })
hl(0, "TodoBgHACK", { fg = p.bbq, bg = p.zest, bold = true })
hl(0, "TodoBgNOTE", { fg = p.bbq, bg = p.sardine, bold = true })
hl(0, "TodoBgPERF", { fg = p.bbq, bg = p.dolly, bold = true })
hl(0, "TodoBgTODO", { fg = p.bbq, bg = p.bok, bold = true })
hl(0, "TodoBgWARN", { fg = p.bbq, bg = p.yam, bold = true })
hl(0, "TodoFgFIX", { fg = p.salmon })
hl(0, "TodoFgHACK", { fg = p.zest })
hl(0, "TodoFgNOTE", { fg = p.sardine })
hl(0, "TodoFgPERF", { fg = p.dolly })
hl(0, "TodoFgTODO", { fg = p.bok })
hl(0, "TodoFgWARN", { fg = p.yam })
hl(0, "TodoSignFIX", { fg = p.salmon })
hl(0, "TodoSignHACK", { fg = p.zest })
hl(0, "TodoSignNOTE", { fg = p.sardine })
hl(0, "TodoSignPERF", { fg = p.dolly })
hl(0, "TodoSignTODO", { fg = p.bok })
hl(0, "TodoSignWARN", { fg = p.yam })
hl(0, "LeapMatch", { fg = p.bok, bold = true, underline = true })
hl(0, "LeapLabel", { fg = p.bbq, bg = p.bok, bold = true })
hl(0, "LeapBackdrop", { fg = p.oyster })
hl(0, "FlashBackdrop", { fg = p.oyster })
hl(0, "FlashLabel", { fg = p.bbq, bg = p.blush, bold = true })
hl(0, "FlashMatch", { fg = p.bok, bold = true })
hl(0, "FlashCurrent", { fg = p.yam, bold = true })
hl(0, "FlashPrompt", { fg = p.smoke, bg = p.bbq })
hl(0, "FlashPromptBorder", { fg = p.charcoal, bg = p.bbq })
hl(0, "MiniJump", { fg = p.bbq, bg = p.blush, bold = true })
hl(0, "MiniJump2dSpot", { fg = p.bbq, bg = p.yam, bold = true })
hl(0, "MiniSurround", { fg = p.bbq, bg = p.bok })
hl(0, "MiniStatuslineModeNormal", { fg = p.butter, bg = p.charple, bold = true })
hl(0, "MiniStatuslineModeInsert", { fg = p.bbq, bg = p.julep, bold = true })
hl(0, "MiniStatuslineModeVisual", { fg = p.bbq, bg = p.tang, bold = true })
hl(0, "MiniStatuslineModeReplace", { fg = p.bbq, bg = p.salmon, bold = true })
hl(0, "MiniStatuslineModeCommand", { fg = p.bbq, bg = p.zest, bold = true })
hl(0, "MiniStatuslineModeOther", { fg = p.bbq, bg = p.lichen, bold = true })
hl(0, "MiniStatuslineDevinfo", { fg = p.smoke, bg = p.charcoal })
hl(0, "MiniStatuslineFileinfo", { fg = p.smoke, bg = p.charcoal })
hl(0, "MiniStatuslineFilename", { fg = p.squid, bg = p.bbq })
hl(0, "MiniStatuslineInactive", { fg = p.squid, bg = p.charcoal })
hl(0, "MiniTablineCurrent", { fg = p.smoke, bg = p.bbq, bold = true })
hl(0, "MiniTablineFill", { bg = p.pepper })
hl(0, "MiniTablineHidden", { fg = p.squid, bg = p.pepper })
hl(0, "MiniTablineVisible", { fg = p.smoke, bg = p.pepper })
hl(0, "MiniTablineModifiedCurrent", { fg = p.yam, bg = p.bbq })
hl(0, "MiniTablineModifiedHidden", { fg = p.yam, bg = p.pepper })
hl(0, "MiniTablineModifiedVisible", { fg = p.yam, bg = p.pepper })
hl(0, "MiniTablineTabpagesection", { fg = p.butter, bg = p.charple, bold = true })
hl(0, "MiniTestPass", { fg = p.bok, bold = true })
hl(0, "MiniTestFail", { fg = p.salmon, bold = true })
hl(0, "MiniTrailspace", { bg = p.salmon })
hl(0, "MiniStarterHeader", { fg = p.larple, bold = true })
hl(0, "MiniStarterFooter", { fg = p.squid, italic = true })
hl(0, "MiniStarterItem", { fg = p.smoke })
hl(0, "MiniStarterItemBullet", { fg = p.iron })
hl(0, "MiniStarterItemPrefix", { fg = p.yam })
hl(0, "MiniStarterSection", { fg = p.lichen, bold = true })
hl(0, "MiniStarterQuery", { fg = p.bok })
hl(0, "MiniStarterInactive", { fg = p.squid, italic = true })
hl(0, "MiniCompletionActiveParameter", { underline = true, sp = p.charple })
hl(0, "MiniCursorword", { underline = true, sp = p.squid })
hl(0, "MiniCursorwordCurrent", { underline = true, sp = p.squid })
hl(0, "NavicIconsFile", { fg = p.sardine })
hl(0, "NavicIconsModule", { fg = p.salmon })
hl(0, "NavicIconsNamespace", { fg = p.salmon })
hl(0, "NavicIconsPackage", { fg = p.orchid })
hl(0, "NavicIconsClass", { fg = p.salt })
hl(0, "NavicIconsMethod", { fg = p.sardine })
hl(0, "NavicIconsProperty", { fg = p.guppy })
hl(0, "NavicIconsField", { fg = p.guppy })
hl(0, "NavicIconsConstructor", { fg = p.salt })
hl(0, "NavicIconsEnum", { fg = p.salt })
hl(0, "NavicIconsInterface", { fg = p.salt })
hl(0, "NavicIconsFunction", { fg = p.sardine })
hl(0, "NavicIconsVariable", { fg = p.sash })
hl(0, "NavicIconsConstant", { fg = p.bok })
hl(0, "NavicIconsString", { fg = p.yam })
hl(0, "NavicIconsNumber", { fg = p.bok })
hl(0, "NavicIconsBoolean", { fg = p.sardine })
hl(0, "NavicIconsArray", { fg = p.bok })
hl(0, "NavicIconsObject", { fg = p.salt })
hl(0, "NavicIconsKey", { fg = p.lichen })
hl(0, "NavicIconsNull", { fg = p.bok })
hl(0, "NavicIconsEnumMember", { fg = p.bok })
hl(0, "NavicIconsStruct", { fg = p.salt })
hl(0, "NavicIconsEvent", { fg = p.tuna })
hl(0, "NavicIconsOperator", { fg = p.salmon })
hl(0, "NavicIconsTypeParameter", { fg = p.guppy })
hl(0, "NavicText", { fg = p.smoke })
hl(0, "NavicSeparator", { fg = p.squid })
hl(0, "AerialNormal", { fg = p.smoke, bg = p.bbq })
hl(0, "AerialLine", { bg = p.charcoal })
hl(0, "AerialGuide", { fg = p.iron })
hl(0, "AerialArrayIcon", { fg = p.bok })
hl(0, "AerialBooleanIcon", { fg = p.sardine })
hl(0, "AerialClassIcon", { fg = p.salt })
hl(0, "AerialConstantIcon", { fg = p.bok })
hl(0, "AerialConstructorIcon", { fg = p.salt })
hl(0, "AerialEnumIcon", { fg = p.salt })
hl(0, "AerialEnumMemberIcon", { fg = p.bok })
hl(0, "AerialEventIcon", { fg = p.tuna })
hl(0, "AerialFieldIcon", { fg = p.guppy })
hl(0, "AerialFileIcon", { fg = p.sardine })
hl(0, "AerialFunctionIcon", { fg = p.sardine })
hl(0, "AerialInterfaceIcon", { fg = p.salt })
hl(0, "AerialKeyIcon", { fg = p.lichen })
hl(0, "AerialMethodIcon", { fg = p.anchovy })
hl(0, "AerialModuleIcon", { fg = p.salmon })
hl(0, "AerialNamespaceIcon", { fg = p.salmon })
hl(0, "AerialNullIcon", { fg = p.bok })
hl(0, "AerialNumberIcon", { fg = p.bok })
hl(0, "AerialObjectIcon", { fg = p.salt })
hl(0, "AerialOperatorIcon", { fg = p.salmon })
hl(0, "AerialPackageIcon", { fg = p.orchid })
hl(0, "AerialPropertyIcon", { fg = p.guppy })
hl(0, "AerialStringIcon", { fg = p.yam })
hl(0, "AerialStructIcon", { fg = p.salt })
hl(0, "AerialTypeParameterIcon", { fg = p.guppy })
hl(0, "AerialVariableIcon", { fg = p.sash })
hl(0, "barbecue_separator", { fg = p.squid })
hl(0, "barbecue_dirname", { fg = p.squid })
hl(0, "barbecue_basename", { fg = p.smoke, bold = true })
hl(0, "barbecue_context", { fg = p.smoke })
hl(0, "barbecue_context_file", { fg = p.sardine })
hl(0, "barbecue_context_module", { fg = p.salmon })
hl(0, "barbecue_context_namespace", { fg = p.salmon })
hl(0, "barbecue_context_package", { fg = p.orchid })
hl(0, "barbecue_context_class", { fg = p.salt })
hl(0, "barbecue_context_method", { fg = p.sardine })
hl(0, "barbecue_context_property", { fg = p.guppy })
hl(0, "barbecue_context_field", { fg = p.guppy })
hl(0, "barbecue_context_constructor", { fg = p.salt })
hl(0, "barbecue_context_enum", { fg = p.salt })
hl(0, "barbecue_context_interface", { fg = p.salt })
hl(0, "barbecue_context_function", { fg = p.sardine })
hl(0, "barbecue_context_variable", { fg = p.sash })
hl(0, "barbecue_context_constant", { fg = p.bok })
hl(0, "barbecue_context_string", { fg = p.yam })
hl(0, "barbecue_context_number", { fg = p.bok })
hl(0, "barbecue_context_boolean", { fg = p.sardine })
hl(0, "barbecue_context_array", { fg = p.bok })
hl(0, "barbecue_context_object", { fg = p.salt })
hl(0, "barbecue_context_key", { fg = p.lichen })
hl(0, "barbecue_context_null", { fg = p.bok })
hl(0, "barbecue_context_enum_member", { fg = p.bok })
hl(0, "barbecue_context_struct", { fg = p.salt })
hl(0, "barbecue_context_event", { fg = p.tuna })
hl(0, "barbecue_context_operator", { fg = p.salmon })
hl(0, "barbecue_context_type_parameter", { fg = p.guppy })
hl(0, "DapBreakpoint", { fg = p.tuna })
hl(0, "DapBreakpointCondition", { fg = p.zest })
hl(0, "DapBreakpointRejected", { fg = p.squid })
hl(0, "DapLogPoint", { fg = p.lichen })
hl(0, "DapStopped", { fg = p.bok })
hl(0, "DapUIVariable", { fg = p.sash })
hl(0, "DapUIScope", { fg = p.lichen })
hl(0, "DapUIType", { fg = p.salt })
hl(0, "DapUIValue", { fg = p.sash })
hl(0, "DapUIModifiedValue", { fg = p.yam, bold = true })
hl(0, "DapUIDecoration", { fg = p.lichen })
hl(0, "DapUIThread", { fg = p.bok })
hl(0, "DapUIStoppedThread", { fg = p.lichen })
hl(0, "DapUIFrameName", { fg = p.smoke })
hl(0, "DapUISource", { fg = p.salmon })
hl(0, "DapUILineNumber", { fg = p.lichen })
hl(0, "DapUIFloatBorder", { fg = p.hazy, bg = p.bbq })
hl(0, "DapUIWatchesEmpty", { fg = p.salmon })
hl(0, "DapUIWatchesValue", { fg = p.bok })
hl(0, "DapUIWatchesError", { fg = p.salmon })
hl(0, "DapUIBreakpointsPath", { fg = p.lichen })
hl(0, "DapUIBreakpointsInfo", { fg = p.bok })
hl(0, "DapUIBreakpointsCurrentLine", { fg = p.bok, bold = true })
hl(0, "DapUIBreakpointsLine", { fg = p.lichen })
hl(0, "DapUIBreakpointsDisabledLine", { fg = p.squid })
hl(0, "DapUICurrentFrameName", { fg = p.bok, bold = true })
hl(0, "DapUIStepOver", { fg = p.lichen })
hl(0, "DapUIStepInto", { fg = p.lichen })
hl(0, "DapUIStepBack", { fg = p.lichen })
hl(0, "DapUIStepOut", { fg = p.lichen })
hl(0, "DapUIStop", { fg = p.salmon })
hl(0, "DapUIPlayPause", { fg = p.bok })
hl(0, "DapUIRestart", { fg = p.bok })
hl(0, "DapUIUnavailable", { fg = p.squid })
hl(0, "NeotestAdapterName", { fg = p.mauve, bold = true })
hl(0, "NeotestBorder", { fg = p.charple })
hl(0, "NeotestDir", { fg = p.anchovy })
hl(0, "NeotestExpandMarker", { fg = p.squid })
hl(0, "NeotestFailed", { fg = p.salmon })
hl(0, "NeotestFile", { fg = p.anchovy })
hl(0, "NeotestFocused", { bold = true })
hl(0, "NeotestIndent", { fg = p.iron })
hl(0, "NeotestMarked", { fg = p.yam, bold = true })
hl(0, "NeotestNamespace", { fg = p.salmon })
hl(0, "NeotestPassed", { fg = p.bok })
hl(0, "NeotestRunning", { fg = p.zest })
hl(0, "NeotestSkipped", { fg = p.oyster })
hl(0, "NeotestTarget", { fg = p.lilac })
hl(0, "NeotestTest", { fg = p.smoke })
hl(0, "NeotestWinSelect", { fg = p.lichen, bold = true })
hl(0, "NeotestUnknown", { fg = p.squid })
hl(0, "NeotestWatching", { fg = p.zest })
hl(0, "NeogitBranch", { fg = p.dolly })
hl(0, "NeogitRemote", { fg = p.blush })
hl(0, "NeogitHunkHeader", { fg = p.smoke, bg = p.charcoal })
hl(0, "NeogitHunkHeaderHighlight", { fg = p.ash, bg = p.charcoal })
hl(0, "NeogitDiffContextHighlight", { bg = p.pepper })
hl(0, "NeogitDiffDeleteHighlight", { fg = p.salmon, bg = p.pepper })
hl(0, "NeogitDiffAddHighlight", { fg = p.bok, bg = p.pepper })
hl(0, "NeogitNotificationInfo", { fg = p.sardine })
hl(0, "NeogitNotificationWarning", { fg = p.zest })
hl(0, "NeogitNotificationError", { fg = p.salmon })
hl(0, "NeogitChangeModified", { fg = p.yam })
hl(0, "NeogitChangeAdded", { fg = p.bok })
hl(0, "NeogitChangeDeleted", { fg = p.tuna })
hl(0, "NeogitChangeRenamed", { fg = p.lilac })
hl(0, "NeogitChangeUpdated", { fg = p.yam })
hl(0, "NeogitChangeCopied", { fg = p.lichen })
hl(0, "NeogitChangeUnmerged", { fg = p.tuna })
hl(0, "NeogitChangeNewFile", { fg = p.bok })
hl(0, "OverseerPENDING", { fg = p.zest })
hl(0, "OverseerRUNNING", { fg = p.sardine })
hl(0, "OverseerSUCCESS", { fg = p.bok })
hl(0, "OverseerCANCELED", { fg = p.squid })
hl(0, "OverseerFAILURE", { fg = p.salmon })
hl(0, "OverseerTask", { fg = p.smoke })
hl(0, "OverseerTaskBorder", { fg = p.hazy, bg = p.bbq })
hl(0, "OverseerOutput", { fg = p.smoke })
hl(0, "OverseerComponent", { fg = p.lichen })
hl(0, "OverseerField", { fg = p.guppy })
hl(0, "HarpoonBorder", { fg = p.hazy, bg = p.bbq })
hl(0, "HarpoonWindow", { fg = p.smoke, bg = p.bbq })
hl(0, "FidgetTask", { fg = p.squid })
hl(0, "FidgetTitle", { fg = p.mauve, bold = true })
hl(0, "LightBulbSign", { fg = p.zest })
hl(0, "LightBulbFloatWin", { fg = p.zest, bg = p.bbq })
hl(0, "LightBulbVirtualText", { fg = p.zest })
hl(0, "SymbolsOutlineConnector", { fg = p.iron })
hl(0, "FocusedSymbol", { bg = p.charcoal })
hl(0, "IlluminatedWordText", { bg = p.charcoal })
hl(0, "IlluminatedWordRead", { bg = p.charcoal })
hl(0, "IlluminatedWordWrite", { bg = p.charcoal, underline = true, sp = p.hazy })
hl(0, "RainbowDelimiterRed", { fg = p.salmon })
hl(0, "RainbowDelimiterYellow", { fg = p.zest })
hl(0, "RainbowDelimiterBlue", { fg = p.sardine })
hl(0, "RainbowDelimiterOrange", { fg = p.yam })
hl(0, "RainbowDelimiterGreen", { fg = p.bok })
hl(0, "RainbowDelimiterViolet", { fg = p.blush })
hl(0, "RainbowDelimiterCyan", { fg = p.lichen })
hl(0, "YankyPut", { link = "IncSearch" })
hl(0, "YankyYanked", { link = "IncSearch" })
hl(0, "Hlargs", { fg = p.yam })
hl(0, "LspReferenceText", { bg = p.charcoal })
hl(0, "LspReferenceRead", { bg = p.charcoal })
hl(0, "LspReferenceWrite", { bg = p.charcoal, underline = true, sp = p.hazy })
hl(0, "LspSignatureActiveParameter", { fg = p.yam, bold = true })
hl(0, "LspCodeLens", { fg = p.squid, italic = true })
hl(0, "LspCodeLensSeparator", { fg = p.iron })
hl(0, "LspInlayHint", { fg = p.squid, bg = p.pepper, italic = true })
hl(0, "@lsp.type.class", { link = "@type" })
hl(0, "@lsp.type.decorator", { link = "@function" })
hl(0, "@lsp.type.enum", { link = "@type" })
hl(0, "@lsp.type.enumMember", { link = "@constant" })
hl(0, "@lsp.type.function", { link = "@function" })
hl(0, "@lsp.type.interface", { link = "@type" })
hl(0, "@lsp.type.macro", { link = "@macro" })
hl(0, "@lsp.type.method", { link = "@function" })
hl(0, "@lsp.type.namespace", { link = "@module" })
hl(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hl(0, "@lsp.type.property", { link = "@property" })
hl(0, "@lsp.type.struct", { link = "@type" })
hl(0, "@lsp.type.type", { link = "@type" })
hl(0, "@lsp.type.typeParameter", { link = "@type" })
hl(0, "@lsp.type.variable", { link = "@variable" })
hl(0, "CursorLineNr", { fg = p.hazy, bg = p.pepper, bold = true })
hl(0, "PmenuSel", { fg = p.ash, bg = p.charple, bold = true })
hl(0, "TelescopeSelection", { fg = p.ash, bg = p.charcoal, bold = true })
hl(0, "BlinkCmpMenuSelection", { fg = p.ash, bg = p.charple, bold = true })
hl(0, "NeoTreeCursorLine", { bg = p.charcoal })
hl(0, "@lsp.mod.deprecated", { fg = p.squid, strikethrough = true })
hl(0, "@type.qualifier", { fg = p.guppy, italic = true })
hl(0, "@markup.environment", { fg = p.salmon })
hl(0, "helpHeader", { fg = p.dolly, bold = true })
hl(0, "helpSectionDelim", { fg = p.squid })
hl(0, "helpHyperTextEntry", { fg = p.sardine })
hl(0, "helpHyperTextJump", { fg = p.sardine, underline = true })
hl(0, "helpExample", { fg = p.yam })
hl(0, "helpCommand", { fg = p.bok, bg = p.bbq })
hl(0, "helpNote", { fg = p.zest, bold = true })
hl(0, "HealthError", { fg = p.salmon })
hl(0, "HealthSuccess", { fg = p.bok })
hl(0, "SnacksPickerBorder", { fg = p.charcoal, bg = p.bbq })
hl(0, "SnacksPickerTitle", { fg = p.butter, bg = p.charple, bold = true })
hl(0, "SnacksPickerInput", { fg = p.sash, bg = p.charcoal })
hl(0, "SnacksPickerInputCursor", { fg = p.bbq, bg = p.sash })
hl(0, "SnacksPickerInputSearch", { fg = p.zest, bold = true })
hl(0, "SnacksPickerList", { fg = p.smoke, bg = p.bbq })
hl(0, "SnacksPickerListCursorLine", { bg = p.charcoal })
hl(0, "SnacksPickerMatch", { fg = p.bok, bold = true })
hl(0, "SnacksPickerDimmed", { fg = p.squid })
hl(0, "SnacksPickerDirectory", { fg = p.mauve })
hl(0, "SnacksPickerDir", { fg = p.mauve })
hl(0, "SnacksPickerFile", { fg = p.sash })
hl(0, "SnacksPickerIcon", { fg = p.sardine })
hl(0, "SnacksPickerIdx", { fg = p.squid })
hl(0, "SnacksPickerLabel", { fg = p.smoke })
hl(0, "SnacksPickerComment", { fg = p.oyster, italic = true })
hl(0, "SnacksPickerPathHidden", { fg = p.squid })
hl(0, "SnacksPickerPathIgnored", { fg = p.squid, italic = true })
hl(0, "SnacksPickerSelected", { fg = p.bok, bold = true })
hl(0, "SnacksPickerPreviewTitle", { fg = p.bbq, bg = p.sardine, bold = true })
hl(0, "SnacksInputIcon", { fg = p.sardine })
hl(0, "SnacksInputNormal", { fg = p.sash, bg = p.charcoal })
hl(0, "SnacksInputBorder", { fg = p.charcoal, bg = p.charcoal })
hl(0, "SnacksInputTitle", { fg = p.butter, bg = p.charple, bold = true })
hl(0, "@attribute", { fg = p.mauve })
hl(0, "@attribute.builtin", { fg = p.mauve })
hl(0, "@number.float", { fg = p.lichen })
hl(0, "@type.definition", { fg = p.salt, bold = true })
hl(0, "@lsp.type.decorator", { link = "@attribute" })
hl(0, "NoiceCmdline", { fg = p.butter, bg = p.darple })
hl(0, "NoiceCmdlinePopup", { fg = p.butter, bg = p.darple })
hl(0, "NoiceCmdlinePopupBorder", { fg = p.hazy, bg = p.darple })
hl(0, "NoiceCmdlinePopupTitle", { fg = p.butter, bg = p.charple, bold = true })

-- Slash filler for the empty middle of the statusline/tabline.
vim.opt.fillchars:append({ stl = "╱", stlnc = "╱" })

hl(0, "BufferLineFill", { fg = p.charple, bg = p.pepper })
hl(0, "BufferLineBuffer", { fg = p.smoke, bg = p.pepper })
hl(0, "BufferLineBufferVisible", { fg = p.smoke, bg = p.pepper })
hl(0, "BufferLineBufferSelected", { fg = p.sash, bg = p.bbq })
hl(0, "BufferLineTabActive", { fg = p.sash, bg = p.bbq, bold = true })

-- Cmdline & messages: darple blocks, butter text everywhere (title, icon, input).
hl(0, "MsgArea", { fg = p.butter, bg = p.darple })
hl(0, "MsgSeparator", { fg = p.hazy, bg = p.darple })
hl(0, "NoiceCmdline", { fg = p.butter, bg = p.darple })
hl(0, "NoiceCmdlinePopup", { fg = p.butter, bg = p.darple })
hl(0, "NoiceCmdlinePopupBorder", { fg = p.hazy, bg = p.darple })
hl(0, "NoiceCmdlinePopupTitle", { fg = p.butter, bg = p.darple, bold = true })
hl(0, "NoiceCmdlineIcon", { fg = p.butter, bg = p.darple })
hl(0, "NoiceCmdlineIconSearch", { fg = p.zest, bg = p.darple })
hl(0, "NoicePopup", { fg = p.butter, bg = p.darple })
hl(0, "NoicePopupBorder", { fg = p.hazy, bg = p.darple })
hl(0, "NoiceMini", { fg = p.butter, bg = p.darple })

-- Message semantic colors (bright set).
hl(0, "WarningMsg", { fg = p.zest, bg = p.darple, bold = true })
hl(0, "ErrorMsg", { fg = p.salmon, bg = p.darple, bold = true })
hl(0, "ModeMsg", { fg = p.bok, bg = p.darple })
hl(0, "MoreMsg", { fg = p.lichen, bg = p.darple })
hl(0, "Question", { fg = p.bok, bg = p.darple, bold = true })

-- Noice per-kind cmdline groups (butter text on the darple block, no purple).
hl(0, "NoiceCmdlinePopupBorderCmdline", { fg = p.butter, bg = p.darple })
hl(0, "NoiceCmdlinePopupTitleCmdline", { fg = p.butter, bg = p.darple, bold = true })
hl(0, "NoiceCmdlineIconCmdline", { fg = p.butter, bg = p.darple })
hl(0, "NoiceCmdlinePopupBorderInput", { fg = p.butter, bg = p.darple })
hl(0, "NoiceCmdlinePopupTitleInput", { fg = p.butter, bg = p.darple, bold = true })
hl(0, "NoiceCmdlineIconInput", { fg = p.butter, bg = p.darple })

-- Notifications: darple container with butter text; icons/titles/borders keep
-- the logical level colors (salmon/zest/sardine/squid).
local notif_levels = { "Error", "Warn", "Info", "Debug", "Trace" }
for _, lvl in ipairs(notif_levels) do
  hl(0, "SnacksNotifier" .. lvl, { fg = p.butter, bg = p.darple })
  hl(0, "SnacksNotifierBody" .. lvl, { fg = p.butter, bg = p.darple })
end
hl(0, "SnacksNotifierHistory", { fg = p.butter, bg = p.darple })
hl(0, "SnacksNotifierHistoryTitle", { fg = p.butter, bg = p.darple, bold = true })
hl(0, "SnacksNotifierMinimal", { fg = p.butter, bg = p.darple })
for _, lvl in ipairs({ "ERROR", "WARN", "INFO", "DEBUG", "TRACE" }) do
  hl(0, "Notify" .. lvl .. "Body", { fg = p.butter, bg = p.darple })
end
hl(0, "NotifyBackground", { fg = p.butter, bg = p.darple })

-- Notification frame: border/title/icon/footer strips share the darple
-- container bg; text stays butter, level accents keep their color.
local level_colors = {
  Error = p.salmon,
  Warn = p.zest,
  Info = p.sardine,
  Debug = p.squid,
  Trace = p.lilac,
}
for _, lvl in ipairs({ "Error", "Warn", "Info", "Debug", "Trace" }) do
  local accent = level_colors[lvl]
  hl(0, "SnacksNotifierBorder" .. lvl, { fg = accent, bg = p.darple })
  hl(0, "SnacksNotifierTitle" .. lvl, { fg = accent, bg = p.darple, bold = true })
  hl(0, "SnacksNotifierIcon" .. lvl, { fg = accent, bg = p.darple })
  hl(0, "SnacksNotifierFooter" .. lvl, { fg = accent, bg = p.darple })
end
hl(0, "NotifyERRORBorder", { fg = p.salmon, bg = p.darple })
hl(0, "NotifyWARNBorder", { fg = p.zest, bg = p.darple })
hl(0, "NotifyINFOBorder", { fg = p.sardine, bg = p.darple })
hl(0, "NotifyDEBUGBorder", { fg = p.squid, bg = p.darple })
hl(0, "NotifyTRACEBorder", { fg = p.lilac, bg = p.darple })
hl(0, "NotifyERRORTitle", { fg = p.salmon, bg = p.darple, bold = true })
hl(0, "NotifyWARNTitle", { fg = p.zest, bg = p.darple, bold = true })
hl(0, "NotifyINFOTitle", { fg = p.sardine, bg = p.darple, bold = true })
hl(0, "NotifyDEBUGTitle", { fg = p.squid, bg = p.darple, bold = true })
hl(0, "NotifyTRACETitle", { fg = p.lilac, bg = p.darple, bold = true })

-- Dashboard slash filler (explicit colored statusline).
hl(0, "DashboardSlash", { fg = p.charple, bg = p.bbq })

-- The statusline fill char (fillchars.stl) renders with hl-StlNormal.
hl(0, "StlNormal", { fg = p.charple, bg = p.bbq })

local heading_colors = { p.dolly, p.guppy, p.lichen, p.bok, p.zest, p.yam }
for i, color in ipairs(heading_colors) do
  hl(0, "@markup.heading." .. i .. ".markdown", { fg = color, bold = true })
end
