vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") then
  vim.cmd("syntax reset")
end

vim.g.colors_name = "samshell"
vim.o.termguicolors = true

local p = {
  white = "#e7e1e3",
  black = "#0e0d0e",
  darker_black = "#0f0e0f",
  black2 = "#1d1b1d",
  one_bg = "#211f21",
  one_bg2 = "#2c292b",
  one_bg3 = "#373436",
  grey = "#4b454b",
  grey_fg = "#4b454b",
  grey_fg2 = "#968e96",
  light_grey = "#e7e1e3",
  red = "#936266",
  baby_pink = "#936266",
  pink = "#8c6293",
  line = "#373436",
  green = "#6c9d70",
  vibrant_green = "#6dab73",
  nord_blue = "#6f6293",
  blue = "#8073a5",
  seablue = "#6f6293",
  yellow = "#7e9c63",
  sun = "#a89871",
  purple = "#8c6293",
  dark_purple = "#373436",
  teal = "#5d8989",
  orange = "#a59173",
  cyan = "#678998",
  none = "NONE",
}

vim.g.terminal_color_0 = p.one_bg
vim.g.terminal_color_1 = p.red
vim.g.terminal_color_2 = p.green
vim.g.terminal_color_3 = p.yellow
vim.g.terminal_color_4 = p.blue
vim.g.terminal_color_5 = p.purple
vim.g.terminal_color_6 = p.cyan
vim.g.terminal_color_7 = p.white
vim.g.terminal_color_8 = p.grey_fg2
vim.g.terminal_color_9 = p.red
vim.g.terminal_color_10 = p.green
vim.g.terminal_color_11 = p.yellow
vim.g.terminal_color_12 = p.blue
vim.g.terminal_color_13 = p.purple
vim.g.terminal_color_14 = p.cyan
vim.g.terminal_color_15 = p.white

local hl = vim.api.nvim_set_hl

-- =============================================================================
-- 1. EDITOR CORE UI
-- =============================================================================

hl(0, "Normal", { fg = p.white, bg = p.black })
hl(0, "NormalNC", { fg = p.white, bg = p.black })
hl(0, "NormalFloat", { fg = p.white, bg = p.one_bg })
hl(0, "FloatBorder", { fg = p.purple, bg = p.one_bg })
hl(0, "FloatTitle", { fg = p.black, bg = p.purple, bold = true })
hl(0, "Cursor", { fg = p.black, bg = p.white })
hl(0, "lCursor", { link = "Cursor" })
hl(0, "CursorIM", { link = "Cursor" })
hl(0, "TermCursor", { fg = p.black, bg = p.white })
hl(0, "TermCursorNC", { fg = p.black, bg = p.grey_fg2 })
hl(0, "CursorLine", { bg = p.one_bg })
hl(0, "CursorColumn", { bg = p.one_bg })
hl(0, "ColorColumn", { bg = p.one_bg })
hl(0, "LineNr", { fg = p.grey })
hl(0, "CursorLineNr", { fg = p.purple, bold = true })
hl(0, "CursorLineFold", { fg = p.yellow, bg = p.one_bg })
hl(0, "CursorLineSign", { fg = p.purple, bg = p.one_bg })
hl(0, "SignColumn", { bg = p.black })
hl(0, "FoldColumn", { fg = p.grey_fg2, bg = p.black })
hl(0, "VertSplit", { fg = p.one_bg3, bg = p.black })
hl(0, "WinSeparator", { fg = p.one_bg3, bg = p.black })
hl(0, "WinBar", { fg = p.purple, bg = p.black, bold = true })
hl(0, "WinBarNC", { fg = p.grey_fg2, bg = p.black })
hl(0, "Visual", { bg = p.one_bg3 })
hl(0, "VisualNOS", { bg = p.one_bg3 })
hl(0, "Search", { fg = p.black, bg = p.purple, bold = true })
hl(0, "IncSearch", { fg = p.black, bg = p.yellow, bold = true })
hl(0, "CurSearch", { fg = p.black, bg = p.orange, bold = true })
hl(0, "Substitute", { fg = p.black, bg = p.red })
hl(0, "Question", { fg = p.green, bold = true })
hl(0, "QuickFixLine", { bg = p.one_bg3, bold = true })
hl(0, "StatusLine", { fg = p.white, bg = p.one_bg })
hl(0, "StatusLineNC", { fg = p.grey_fg2, bg = p.black })
hl(0, "TabLine", { fg = p.grey_fg2, bg = p.black })
hl(0, "TabLineFill", { bg = p.black })
hl(0, "TabLineSel", { fg = p.white, bg = p.one_bg, bold = true })
hl(0, "Title", { fg = p.purple, bold = true })
hl(0, "Directory", { fg = p.blue })
hl(0, "EndOfBuffer", { fg = p.black })
hl(0, "Conceal", { fg = p.grey_fg2 })
hl(0, "NonText", { fg = p.grey })
hl(0, "SpecialKey", { fg = p.grey })
hl(0, "Whitespace", { fg = p.grey })
hl(0, "Pmenu", { fg = p.light_grey, bg = p.one_bg2 })
hl(0, "PmenuSel", { fg = p.black, bg = p.purple, bold = true })
hl(0, "PmenuSbar", { bg = p.one_bg2 })
hl(0, "PmenuThumb", { bg = p.grey_fg2 })
hl(0, "PmenuKind", { fg = p.cyan, bg = p.one_bg2 })
hl(0, "PmenuKindSel", { fg = p.black, bg = p.purple, bold = true })
hl(0, "PmenuExtra", { fg = p.grey_fg2, bg = p.one_bg2 })
hl(0, "PmenuExtraSel", { fg = p.black, bg = p.purple })
hl(0, "WildMenu", { fg = p.black, bg = p.purple, bold = true })
hl(0, "MatchParen", { fg = p.vibrant_green, bold = true, underline = true })
hl(0, "Folded", { fg = p.grey_fg2, bg = p.one_bg, italic = true })
hl(0, "ModeMsg", { fg = p.green, bold = true })
hl(0, "MoreMsg", { fg = p.cyan, bold = true })
hl(0, "WarningMsg", { fg = p.yellow, bold = true })
hl(0, "ErrorMsg", { fg = p.red, bold = true })
hl(0, "MsgArea", { fg = p.white, bg = p.black })
hl(0, "MsgSeparator", { fg = p.one_bg3, bg = p.black })
hl(0, "SpellBad", { undercurl = true, sp = p.red })
hl(0, "SpellCap", { undercurl = true, sp = p.yellow })
hl(0, "SpellLocal", { undercurl = true, sp = p.cyan })
hl(0, "SpellRare", { undercurl = true, sp = p.purple })
hl(0, "DiffAdd", { fg = p.black, bg = p.green })
hl(0, "DiffChange", { fg = p.black, bg = p.yellow })
hl(0, "DiffDelete", { fg = p.black, bg = p.red })
hl(0, "DiffText", { fg = p.black, bg = p.orange, bold = true })
hl(0, "diffAdded", { fg = p.green })
hl(0, "diffRemoved", { fg = p.red })
hl(0, "diffChanged", { fg = p.yellow })
hl(0, "diffOldFile", { fg = p.red })
hl(0, "diffNewFile", { fg = p.green })
hl(0, "diffFile", { fg = p.cyan })
hl(0, "diffLine", { fg = p.grey_fg2 })
hl(0, "diffIndexLine", { fg = p.purple })

-- =============================================================================
-- 2. SYNTAX HIGHLIGHTING (Standard & Treesitter)
-- =============================================================================

hl(0, "Comment", { fg = p.grey_fg2, italic = true })
hl(0, "Constant", { fg = p.orange })
hl(0, "String", { fg = p.orange })
hl(0, "Character", { fg = p.green })
hl(0, "Number", { fg = p.orange })
hl(0, "Boolean", { fg = p.orange, bold = true })
hl(0, "Float", { fg = p.orange })
hl(0, "Identifier", { fg = p.white })
hl(0, "Function", { fg = p.blue })
hl(0, "Statement", { fg = p.purple })
hl(0, "Conditional", { fg = p.purple, italic = true })
hl(0, "Repeat", { fg = p.purple, italic = true })
hl(0, "Label", { fg = p.purple })
hl(0, "Operator", { fg = p.cyan })
hl(0, "Keyword", { fg = p.purple, bold = true })
hl(0, "Exception", { fg = p.red, bold = true })
hl(0, "PreProc", { fg = p.yellow })
hl(0, "Include", { fg = p.purple })
hl(0, "Define", { fg = p.purple })
hl(0, "Macro", { fg = p.teal })
hl(0, "PreCondit", { fg = p.purple })
hl(0, "Type", { fg = p.yellow })
hl(0, "StorageClass", { fg = p.purple })
hl(0, "Structure", { fg = p.yellow })
hl(0, "Typedef", { fg = p.yellow })
hl(0, "Special", { fg = p.teal })
hl(0, "SpecialChar", { fg = p.vibrant_green })
hl(0, "Tag", { fg = p.purple })
hl(0, "Delimiter", { fg = p.white })
hl(0, "SpecialComment", { fg = p.cyan, italic = true })
hl(0, "Debug", { fg = p.red })
hl(0, "Underlined", { underline = true })
hl(0, "Ignore", { fg = p.grey })
hl(0, "Error", { fg = p.red, bold = true })
hl(0, "Todo", { fg = p.black, bg = p.yellow, bold = true })
hl(0, "@variable", { fg = p.white })
hl(0, "@variable.builtin", { fg = p.red })
hl(0, "@variable.parameter", { fg = p.sun })
hl(0, "@variable.member", { fg = p.cyan })
hl(0, "@constant", { fg = p.orange })
hl(0, "@constant.builtin", { fg = p.orange, bold = true })
hl(0, "@constant.macro", { fg = p.teal })
hl(0, "@module", { fg = p.yellow })
hl(0, "@label", { fg = p.purple })
hl(0, "@function", { fg = p.blue })
hl(0, "@function.builtin", { fg = p.seablue })
hl(0, "@function.call", { fg = p.blue })
hl(0, "@function.macro", { fg = p.teal })
hl(0, "@function.method", { fg = p.blue })
hl(0, "@function.method.call", { fg = p.blue })
hl(0, "@constructor", { fg = p.yellow })
hl(0, "@parameter", { fg = p.sun })
hl(0, "@keyword", { fg = p.purple, bold = true })
hl(0, "@keyword.function", { fg = p.purple, bold = true })
hl(0, "@keyword.operator", { fg = p.purple })
hl(0, "@keyword.import", { fg = p.purple })
hl(0, "@keyword.return", { fg = p.purple, italic = true })
hl(0, "@keyword.conditional", { fg = p.purple, italic = true })
hl(0, "@keyword.repeat", { fg = p.purple, italic = true })
hl(0, "@keyword.exception", { fg = p.red, bold = true })
hl(0, "@keyword.storage", { fg = p.purple })
hl(0, "@string", { fg = p.orange })
hl(0, "@string.documentation", { fg = p.green, italic = true })
hl(0, "@string.regexp", { fg = p.vibrant_green })
hl(0, "@string.escape", { fg = p.vibrant_green })
hl(0, "@string.special", { fg = p.vibrant_green })
hl(0, "@string.special.symbol", { fg = p.cyan })
hl(0, "@string.special.url", { fg = p.seablue, underline = true })
hl(0, "@string.special.path", { fg = p.green })
hl(0, "@character", { fg = p.green })
hl(0, "@character.special", { fg = p.vibrant_green })
hl(0, "@type", { fg = p.yellow })
hl(0, "@type.builtin", { fg = p.yellow, italic = true })
hl(0, "@type.definition", { fg = p.yellow })
hl(0, "@type.qualifier", { fg = p.purple })
hl(0, "@attribute", { fg = p.teal })
hl(0, "@property", { fg = p.cyan })
hl(0, "@field", { fg = p.cyan })
hl(0, "@operator", { fg = p.cyan })
hl(0, "@punctuation.delimiter", { fg = p.white })
hl(0, "@punctuation.bracket", { fg = p.white })
hl(0, "@punctuation.special", { fg = p.cyan })
hl(0, "@comment", { fg = p.grey_fg2, italic = true })
hl(0, "@comment.documentation", { fg = p.grey_fg2, italic = true })
hl(0, "@comment.error", { fg = p.red, bg = p.one_bg })
hl(0, "@comment.warning", { fg = p.yellow, bg = p.one_bg })
hl(0, "@comment.todo", { fg = p.black, bg = p.yellow, bold = true })
hl(0, "@comment.note", { fg = p.cyan, bg = p.one_bg })
hl(0, "@tag", { fg = p.purple })
hl(0, "@tag.builtin", { fg = p.purple, bold = true })
hl(0, "@tag.attribute", { fg = p.cyan })
hl(0, "@tag.delimiter", { fg = p.white })
hl(0, "@markup.strong", { bold = true })
hl(0, "@markup.italic", { italic = true })
hl(0, "@markup.strikethrough", { strikethrough = true })
hl(0, "@markup.underline", { underline = true })
hl(0, "@markup.heading", { fg = p.purple, bold = true })
hl(0, "@markup.heading.1", { fg = p.purple, bold = true })
hl(0, "@markup.heading.2", { fg = p.blue, bold = true })
hl(0, "@markup.heading.3", { fg = p.cyan, bold = true })
hl(0, "@markup.heading.4", { fg = p.green, bold = true })
hl(0, "@markup.heading.5", { fg = p.yellow, bold = true })
hl(0, "@markup.heading.6", { fg = p.orange, bold = true })
hl(0, "@markup.quote", { fg = p.grey_fg2, italic = true })
hl(0, "@markup.math", { fg = p.orange })
hl(0, "@markup.environment", { fg = p.purple })
hl(0, "@markup.link", { fg = p.cyan, underline = true })
hl(0, "@markup.link.label", { fg = p.cyan })
hl(0, "@markup.link.url", { fg = p.seablue, underline = true })
hl(0, "@markup.raw", { fg = p.green })
hl(0, "@markup.raw.block", { fg = p.green })
hl(0, "@markup.list", { fg = p.purple })
hl(0, "@markup.list.checked", { fg = p.green })
hl(0, "@markup.list.unchecked", { fg = p.grey_fg2 })
hl(0, "@number", { fg = p.orange })
hl(0, "@number.float", { fg = p.orange })
hl(0, "@boolean", { fg = p.orange, bold = true })
hl(0, "@diff.plus", { fg = p.green })
hl(0, "@diff.minus", { fg = p.red })
hl(0, "@diff.delta", { fg = p.yellow })
hl(0, "@lsp.type.namespace.lua", { fg = p.yellow })
hl(0, "@lsp.type.property.lua", { fg = p.cyan })
hl(0, "@variable.builtin.python", { fg = p.red, italic = true })
hl(0, "@variable.builtin.javascript", { fg = p.red })
hl(0, "@variable.builtin.typescript", { fg = p.red })

-- =============================================================================
-- 3. LSP & DIAGNOSTICS
-- =============================================================================

hl(0, "LspReferenceText", { bg = p.one_bg3 })
hl(0, "LspReferenceRead", { bg = p.one_bg3 })
hl(0, "LspReferenceWrite", { bg = p.one_bg3, underline = true })
hl(0, "LspSignatureActiveParameter", { fg = p.orange, bold = true })
hl(0, "LspCodeLens", { fg = p.grey_fg2, italic = true })
hl(0, "LspCodeLensSeparator", { fg = p.grey })
hl(0, "LspInlayHint", { fg = p.grey_fg2, bg = p.one_bg, italic = true })
hl(0, "DiagnosticError", { fg = p.red })
hl(0, "DiagnosticWarn", { fg = p.yellow })
hl(0, "DiagnosticInfo", { fg = p.seablue })
hl(0, "DiagnosticHint", { fg = p.teal })
hl(0, "DiagnosticOk", { fg = p.green })
hl(0, "DiagnosticUnderlineError", { undercurl = true, sp = p.red })
hl(0, "DiagnosticUnderlineWarn", { undercurl = true, sp = p.yellow })
hl(0, "DiagnosticUnderlineInfo", { undercurl = true, sp = p.seablue })
hl(0, "DiagnosticUnderlineHint", { undercurl = true, sp = p.teal })
hl(0, "DiagnosticUnderlineOk", { undercurl = true, sp = p.green })
hl(0, "DiagnosticVirtualTextError", { fg = p.red, bg = p.one_bg })
hl(0, "DiagnosticVirtualTextWarn", { fg = p.yellow, bg = p.one_bg })
hl(0, "DiagnosticVirtualTextInfo", { fg = p.seablue, bg = p.one_bg })
hl(0, "DiagnosticVirtualTextHint", { fg = p.teal, bg = p.one_bg })
hl(0, "DiagnosticVirtualTextOk", { fg = p.green, bg = p.one_bg })
hl(0, "DiagnosticFloatingError", { fg = p.red, bg = p.one_bg })
hl(0, "DiagnosticFloatingWarn", { fg = p.yellow, bg = p.one_bg })
hl(0, "DiagnosticFloatingInfo", { fg = p.seablue, bg = p.one_bg })
hl(0, "DiagnosticFloatingHint", { fg = p.teal, bg = p.one_bg })
hl(0, "DiagnosticFloatingOk", { fg = p.green, bg = p.one_bg })
hl(0, "DiagnosticSignError", { fg = p.red, bg = p.black })
hl(0, "DiagnosticSignWarn", { fg = p.yellow, bg = p.black })
hl(0, "DiagnosticSignInfo", { fg = p.seablue, bg = p.black })
hl(0, "DiagnosticSignHint", { fg = p.teal, bg = p.black })
hl(0, "DiagnosticSignOk", { fg = p.green, bg = p.black })
hl(0, "@lsp.type.class", { link = "@type" })
hl(0, "@lsp.type.decorator", { link = "@function" })
hl(0, "@lsp.type.enum", { link = "@type" })
hl(0, "@lsp.type.enumMember", { link = "@constant" })
hl(0, "@lsp.type.function", { link = "@function" })
hl(0, "@lsp.type.interface", { link = "@type" })
hl(0, "@lsp.type.macro", { link = "@macro" })
hl(0, "@lsp.type.method", { link = "@function.method" })
hl(0, "@lsp.type.namespace", { link = "@module" })
hl(0, "@lsp.type.parameter", { link = "@parameter" })
hl(0, "@lsp.type.property", { link = "@property" })
hl(0, "@lsp.type.struct", { link = "@type" })
hl(0, "@lsp.type.type", { link = "@type" })
hl(0, "@lsp.type.typeParameter", { link = "@type" })
hl(0, "@lsp.type.variable", { link = "@variable" })

-- =============================================================================
-- 4. LAZYVIM PLUGINS
-- =============================================================================

hl(0, "LazyNormal", { fg = p.white, bg = p.one_bg })
hl(0, "LazyH1", { fg = p.black, bg = p.purple, bold = true })
hl(0, "LazyH2", { fg = p.purple, bold = true })
hl(0, "LazyButton", { fg = p.white, bg = p.one_bg3 })
hl(0, "LazyButtonActive", { fg = p.black, bg = p.purple, bold = true })
hl(0, "LazyComment", { fg = p.grey_fg2, italic = true })
hl(0, "LazyCommit", { fg = p.green })
hl(0, "LazyCommitIssue", { fg = p.red })
hl(0, "LazyCommitType", { fg = p.purple })
hl(0, "LazyCommitScope", { fg = p.cyan })
hl(0, "LazyDimmed", { fg = p.grey_fg2 })
hl(0, "LazyDir", { fg = p.cyan })
hl(0, "LazyLocal", { fg = p.teal })
hl(0, "LazyProp", { fg = p.cyan })
hl(0, "LazyReasonCmd", { fg = p.yellow })
hl(0, "LazyReasonEvent", { fg = p.orange })
hl(0, "LazyReasonFt", { fg = p.purple })
hl(0, "LazyReasonImport", { fg = p.cyan })
hl(0, "LazyReasonKeys", { fg = p.blue })
hl(0, "LazyReasonPlugin", { fg = p.green })
hl(0, "LazyReasonRuntime", { fg = p.seablue })
hl(0, "LazyReasonSource", { fg = p.teal })
hl(0, "LazyReasonStart", { fg = p.vibrant_green })
hl(0, "LazySpecial", { fg = p.teal })
hl(0, "LazyTaskError", { fg = p.red })
hl(0, "LazyTaskOutput", { fg = p.white })
hl(0, "LazyUrl", { fg = p.seablue, underline = true })
hl(0, "LazyValue", { fg = p.cyan })
hl(0, "MasonNormal", { fg = p.white, bg = p.one_bg })
hl(0, "MasonHeader", { fg = p.black, bg = p.purple, bold = true })
hl(0, "MasonHeaderSecondary", { fg = p.black, bg = p.cyan, bold = true })
hl(0, "MasonHighlight", { fg = p.purple })
hl(0, "MasonHighlightBlock", { fg = p.black, bg = p.purple })
hl(0, "MasonHighlightBlockBold", { fg = p.black, bg = p.purple, bold = true })
hl(0, "MasonHighlightSecondary", { fg = p.cyan })
hl(0, "MasonHighlightBlockSecondary", { fg = p.black, bg = p.cyan })
hl(0, "MasonHighlightBlockBoldSecondary", { fg = p.black, bg = p.cyan, bold = true })
hl(0, "MasonMuted", { fg = p.grey_fg2 })
hl(0, "MasonMutedBlock", { fg = p.grey_fg2, bg = p.one_bg3 })
hl(0, "MasonMutedBlockBold", { fg = p.grey_fg2, bg = p.one_bg3, bold = true })
hl(0, "MasonError", { fg = p.red })
hl(0, "MasonWarning", { fg = p.yellow })
hl(0, "MasonHeading", { fg = p.purple, bold = true })
hl(0, "TelescopeNormal", { fg = p.white, bg = p.one_bg })
hl(0, "TelescopeBorder", { fg = p.one_bg3, bg = p.one_bg })
hl(0, "TelescopeTitle", { fg = p.black, bg = p.purple, bold = true })
hl(0, "TelescopePromptNormal", { fg = p.white, bg = p.one_bg2 })
hl(0, "TelescopePromptBorder", { fg = p.one_bg2, bg = p.one_bg2 })
hl(0, "TelescopePromptTitle", { fg = p.black, bg = p.purple, bold = true })
hl(0, "TelescopePromptPrefix", { fg = p.purple, bg = p.one_bg2 })
hl(0, "TelescopePromptCounter", { fg = p.grey_fg2, bg = p.one_bg2 })
hl(0, "TelescopePreviewNormal", { fg = p.white, bg = p.one_bg })
hl(0, "TelescopePreviewBorder", { fg = p.one_bg, bg = p.one_bg })
hl(0, "TelescopePreviewTitle", { fg = p.black, bg = p.green, bold = true })
hl(0, "TelescopeResultsNormal", { fg = p.white, bg = p.one_bg })
hl(0, "TelescopeResultsBorder", { fg = p.one_bg, bg = p.one_bg })
hl(0, "TelescopeResultsTitle", { fg = p.black, bg = p.cyan, bold = true })
hl(0, "TelescopeSelection", { fg = p.white, bg = p.one_bg3, bold = true })
hl(0, "TelescopeSelectionCaret", { fg = p.purple, bg = p.one_bg3 })
hl(0, "TelescopeMultiSelection", { fg = p.cyan, bg = p.one_bg3 })
hl(0, "TelescopeMatching", { fg = p.vibrant_green, bold = true })
hl(0, "TelescopePreviewLine", { bg = p.one_bg3 })
hl(0, "TelescopePreviewMatch", { fg = p.black, bg = p.purple })
hl(0, "NeoTreeNormal", { fg = p.light_grey, bg = p.darker_black })
hl(0, "NeoTreeNormalNC", { fg = p.light_grey, bg = p.darker_black })
hl(0, "NeoTreeWinSeparator", { fg = p.black, bg = p.black })
hl(0, "NeoTreeEndOfBuffer", { fg = p.darker_black, bg = p.darker_black })
hl(0, "NeoTreeRootName", { fg = p.purple, bold = true })
hl(0, "NeoTreeDirectoryName", { fg = p.blue })
hl(0, "NeoTreeDirectoryIcon", { fg = p.blue })
hl(0, "NeoTreeFileName", { fg = p.light_grey })
hl(0, "NeoTreeFileIcon", { fg = p.white })
hl(0, "NeoTreeFileNameOpened", { fg = p.cyan, bold = true })
hl(0, "NeoTreeIndentMarker", { fg = p.grey })
hl(0, "NeoTreeExpander", { fg = p.grey_fg2 })
hl(0, "NeoTreeSymbolicLinkTarget", { fg = p.cyan })
hl(0, "NeoTreeGitAdded", { fg = p.green })
hl(0, "NeoTreeGitConflict", { fg = p.red, bold = true })
hl(0, "NeoTreeGitDeleted", { fg = p.red })
hl(0, "NeoTreeGitIgnored", { fg = p.grey_fg2, italic = true })
hl(0, "NeoTreeGitModified", { fg = p.yellow })
hl(0, "NeoTreeGitUnstaged", { fg = p.orange })
hl(0, "NeoTreeGitUntracked", { fg = p.cyan })
hl(0, "NeoTreeGitStaged", { fg = p.green })
hl(0, "NeoTreeFloatBorder", { fg = p.purple, bg = p.one_bg })
hl(0, "NeoTreeFloatTitle", { fg = p.black, bg = p.purple, bold = true })
hl(0, "NeoTreeTitleBar", { fg = p.black, bg = p.purple, bold = true })
hl(0, "NeoTreeCursorLine", { bg = p.one_bg })
hl(0, "NeoTreeDimText", { fg = p.grey })
hl(0, "NeoTreeFilterTerm", { fg = p.vibrant_green, bold = true })
hl(0, "NeoTreeTabActive", { fg = p.white, bg = p.one_bg, bold = true })
hl(0, "NeoTreeTabInactive", { fg = p.grey_fg2, bg = p.darker_black })
hl(0, "NeoTreeTabSeparatorActive", { fg = p.one_bg, bg = p.one_bg })
hl(0, "NeoTreeTabSeparatorInactive", { fg = p.darker_black, bg = p.darker_black })
hl(0, "NvimTreeNormal", { link = "NeoTreeNormal" })
hl(0, "NvimTreeNormalNC", { link = "NeoTreeNormalNC" })
hl(0, "NvimTreeWinSeparator", { link = "NeoTreeWinSeparator" })
hl(0, "NvimTreeRootFolder", { link = "NeoTreeRootName" })
hl(0, "NvimTreeFolderName", { link = "NeoTreeDirectoryName" })
hl(0, "NvimTreeFolderIcon", { link = "NeoTreeDirectoryIcon" })
hl(0, "NvimTreeEmptyFolderName", { link = "NeoTreeDirectoryName" })
hl(0, "NvimTreeOpenedFolderName", { fg = p.cyan, bold = true })
hl(0, "GitSignsAdd", { fg = p.green, bg = p.black })
hl(0, "GitSignsChange", { fg = p.yellow, bg = p.black })
hl(0, "GitSignsDelete", { fg = p.red, bg = p.black })
hl(0, "GitSignsAddNr", { fg = p.green, bg = p.black })
hl(0, "GitSignsChangeNr", { fg = p.yellow, bg = p.black })
hl(0, "GitSignsDeleteNr", { fg = p.red, bg = p.black })
hl(0, "GitSignsAddLn", { fg = p.black, bg = p.green })
hl(0, "GitSignsChangeLn", { fg = p.black, bg = p.yellow })
hl(0, "GitSignsDeleteLn", { fg = p.black, bg = p.red })
hl(0, "GitSignsAddInline", { fg = p.black, bg = p.green })
hl(0, "GitSignsChangeInline", { fg = p.black, bg = p.yellow })
hl(0, "GitSignsDeleteInline", { fg = p.black, bg = p.red })
hl(0, "GitSignsCurrentLineBlame", { fg = p.grey_fg2, italic = true })
hl(0, "GitSignsAddPreview", { fg = p.green })
hl(0, "GitSignsDeletePreview", { fg = p.red })
hl(0, "GitSignsAddVirtLn", { fg = p.black, bg = p.green })
hl(0, "GitSignsDeleteVirtLn", { fg = p.black, bg = p.red })
hl(0, "NotifyERRORBorder", { fg = p.red, bg = p.one_bg })
hl(0, "NotifyERRORIcon", { fg = p.red })
hl(0, "NotifyERRORTitle", { fg = p.red, bold = true })
hl(0, "NotifyERRORBody", { fg = p.white, bg = p.one_bg })
hl(0, "NotifyWARNBorder", { fg = p.yellow, bg = p.one_bg })
hl(0, "NotifyWARNIcon", { fg = p.yellow })
hl(0, "NotifyWARNTitle", { fg = p.yellow, bold = true })
hl(0, "NotifyWARNBody", { fg = p.white, bg = p.one_bg })
hl(0, "NotifyINFOBorder", { fg = p.seablue, bg = p.one_bg })
hl(0, "NotifyINFOIcon", { fg = p.seablue })
hl(0, "NotifyINFOTitle", { fg = p.seablue, bold = true })
hl(0, "NotifyINFOBody", { fg = p.white, bg = p.one_bg })
hl(0, "NotifyDEBUGBorder", { fg = p.grey_fg2, bg = p.one_bg })
hl(0, "NotifyDEBUGIcon", { fg = p.grey_fg2 })
hl(0, "NotifyDEBUGTitle", { fg = p.grey_fg2, bold = true })
hl(0, "NotifyDEBUGBody", { fg = p.white, bg = p.one_bg })
hl(0, "NotifyTRACEBorder", { fg = p.purple, bg = p.one_bg })
hl(0, "NotifyTRACEIcon", { fg = p.purple })
hl(0, "NotifyTRACETitle", { fg = p.purple, bold = true })
hl(0, "NotifyTRACEBody", { fg = p.white, bg = p.one_bg })
hl(0, "NotifyBackground", { bg = p.one_bg })
hl(0, "WhichKey", { fg = p.cyan, bold = true })
hl(0, "WhichKeyGroup", { fg = p.purple })
hl(0, "WhichKeyDesc", { fg = p.white })
hl(0, "WhichKeySeparator", { fg = p.grey_fg2 })
hl(0, "WhichKeyFloat", { bg = p.one_bg })
hl(0, "WhichKeyBorder", { fg = p.purple, bg = p.one_bg })
hl(0, "WhichKeyValue", { fg = p.grey_fg2 })
hl(0, "IblIndent", { fg = p.grey, nocombine = true })
hl(0, "IblWhitespace", { fg = p.grey, nocombine = true })
hl(0, "IblScope", { fg = p.purple, nocombine = true })
hl(0, "IndentBlanklineChar", { fg = p.grey })
hl(0, "IndentBlanklineSpaceChar", { fg = p.grey })
hl(0, "IndentBlanklineContextChar", { fg = p.purple })
hl(0, "IndentBlanklineContextStart", { underline = true, sp = p.purple })
hl(0, "DashboardHeader", { fg = p.purple, bold = true })
hl(0, "DashboardCenter", { fg = p.cyan })
hl(0, "DashboardShortCut", { fg = p.yellow })
hl(0, "DashboardFooter", { fg = p.grey_fg2, italic = true })
hl(0, "AlphaHeader", { fg = p.purple, bold = true })
hl(0, "AlphaButtons", { fg = p.cyan })
hl(0, "AlphaShortcut", { fg = p.yellow, bold = true })
hl(0, "AlphaFooter", { fg = p.grey_fg2, italic = true })
hl(0, "NoicePopup", { fg = p.white, bg = p.one_bg })
hl(0, "NoicePopupBorder", { fg = p.purple, bg = p.one_bg })
hl(0, "NoiceCmdline", { fg = p.white, bg = p.one_bg2 })
hl(0, "NoiceCmdlinePopup", { fg = p.white, bg = p.one_bg2 })
hl(0, "NoiceCmdlinePopupBorder", { fg = p.purple, bg = p.one_bg2 })
hl(0, "NoiceCmdlinePopupTitle", { fg = p.black, bg = p.purple, bold = true })
hl(0, "NoiceCmdlineIcon", { fg = p.cyan })
hl(0, "NoiceCmdlineIconSearch", { fg = p.yellow })
hl(0, "NoiceConfirm", { fg = p.white, bg = p.one_bg })
hl(0, "NoiceConfirmBorder", { fg = p.cyan, bg = p.one_bg })
hl(0, "NoiceMini", { fg = p.white, bg = p.one_bg })
hl(0, "NoiceFormatProgressDone", { fg = p.black, bg = p.green })
hl(0, "NoiceFormatProgressTodo", { fg = p.grey_fg2, bg = p.one_bg3 })
hl(0, "NoiceLspProgressClient", { fg = p.purple })
hl(0, "NoiceLspProgressSpinner", { fg = p.cyan })
hl(0, "NoiceLspProgressTitle", { fg = p.white })
hl(0, "CmpNormal", { fg = p.white, bg = p.one_bg2 })
hl(0, "CmpBorder", { fg = p.one_bg3, bg = p.one_bg2 })
hl(0, "CmpDocumentation", { fg = p.white, bg = p.one_bg })
hl(0, "CmpDocumentationBorder", { fg = p.one_bg3, bg = p.one_bg })
hl(0, "CmpItemAbbr", { fg = p.white })
hl(0, "CmpItemAbbrDeprecated", { fg = p.grey_fg2, strikethrough = true })
hl(0, "CmpItemAbbrMatch", { fg = p.vibrant_green, bold = true })
hl(0, "CmpItemAbbrMatchFuzzy", { fg = p.green, bold = true })
hl(0, "CmpItemMenu", { fg = p.grey_fg2, italic = true })
hl(0, "CmpItemKind", { fg = p.cyan })
hl(0, "CmpItemKindText", { fg = p.white })
hl(0, "CmpItemKindMethod", { fg = p.blue })
hl(0, "CmpItemKindFunction", { fg = p.blue })
hl(0, "CmpItemKindConstructor", { fg = p.yellow })
hl(0, "CmpItemKindField", { fg = p.cyan })
hl(0, "CmpItemKindVariable", { fg = p.white })
hl(0, "CmpItemKindClass", { fg = p.yellow })
hl(0, "CmpItemKindInterface", { fg = p.yellow })
hl(0, "CmpItemKindModule", { fg = p.yellow })
hl(0, "CmpItemKindProperty", { fg = p.cyan })
hl(0, "CmpItemKindUnit", { fg = p.orange })
hl(0, "CmpItemKindValue", { fg = p.orange })
hl(0, "CmpItemKindEnum", { fg = p.yellow })
hl(0, "CmpItemKindKeyword", { fg = p.purple })
hl(0, "CmpItemKindSnippet", { fg = p.teal })
hl(0, "CmpItemKindColor", { fg = p.pink })
hl(0, "CmpItemKindFile", { fg = p.blue })
hl(0, "CmpItemKindReference", { fg = p.cyan })
hl(0, "CmpItemKindFolder", { fg = p.blue })
hl(0, "CmpItemKindEnumMember", { fg = p.orange })
hl(0, "CmpItemKindConstant", { fg = p.orange })
hl(0, "CmpItemKindStruct", { fg = p.yellow })
hl(0, "CmpItemKindEvent", { fg = p.purple })
hl(0, "CmpItemKindOperator", { fg = p.cyan })
hl(0, "CmpItemKindTypeParameter", { fg = p.yellow })
hl(0, "CmpItemKindCopilot", { fg = p.teal })
hl(0, "CmpItemKindCodeium", { fg = p.teal })
hl(0, "CmpItemKindTabNine", { fg = p.teal })
hl(0, "CmpItemKindSuperMaven", { fg = p.teal })
hl(0, "AerialNormal", { fg = p.white, bg = p.one_bg })
hl(0, "AerialLine", { bg = p.one_bg3 })
hl(0, "AerialGuide", { fg = p.grey })
hl(0, "AerialArrayIcon", { fg = p.orange })
hl(0, "AerialBooleanIcon", { fg = p.orange })
hl(0, "AerialClassIcon", { fg = p.yellow })
hl(0, "AerialConstantIcon", { fg = p.orange })
hl(0, "AerialConstructorIcon", { fg = p.yellow })
hl(0, "AerialEnumIcon", { fg = p.yellow })
hl(0, "AerialEnumMemberIcon", { fg = p.orange })
hl(0, "AerialEventIcon", { fg = p.purple })
hl(0, "AerialFieldIcon", { fg = p.cyan })
hl(0, "AerialFileIcon", { fg = p.blue })
hl(0, "AerialFunctionIcon", { fg = p.blue })
hl(0, "AerialInterfaceIcon", { fg = p.yellow })
hl(0, "AerialKeyIcon", { fg = p.cyan })
hl(0, "AerialMethodIcon", { fg = p.blue })
hl(0, "AerialModuleIcon", { fg = p.yellow })
hl(0, "AerialNamespaceIcon", { fg = p.yellow })
hl(0, "AerialNullIcon", { fg = p.orange })
hl(0, "AerialNumberIcon", { fg = p.orange })
hl(0, "AerialObjectIcon", { fg = p.yellow })
hl(0, "AerialOperatorIcon", { fg = p.cyan })
hl(0, "AerialPackageIcon", { fg = p.yellow })
hl(0, "AerialPropertyIcon", { fg = p.cyan })
hl(0, "AerialStringIcon", { fg = p.green })
hl(0, "AerialStructIcon", { fg = p.yellow })
hl(0, "AerialTypeParameterIcon", { fg = p.yellow })
hl(0, "AerialVariableIcon", { fg = p.white })
hl(0, "TroubleNormal", { fg = p.white, bg = p.one_bg })
hl(0, "TroubleText", { fg = p.white })
hl(0, "TroubleCount", { fg = p.purple, bold = true })
hl(0, "TroubleCode", { fg = p.grey_fg2 })
hl(0, "TroubleDirectory", { fg = p.blue })
hl(0, "TroubleSource", { fg = p.grey_fg2 })
hl(0, "TroubleFile", { fg = p.cyan })
hl(0, "TroubleIndent", { fg = p.grey })
hl(0, "TroubleLocation", { fg = p.grey_fg2 })
hl(0, "TroubleFoldIcon", { fg = p.purple })
hl(0, "TroubleTextError", { fg = p.red })
hl(0, "TroubleTextWarning", { fg = p.yellow })
hl(0, "TroubleTextInformation", { fg = p.seablue })
hl(0, "TroubleTextHint", { fg = p.teal })
hl(0, "TroubleSignError", { fg = p.red })
hl(0, "TroubleSignWarning", { fg = p.yellow })
hl(0, "TroubleSignInformation", { fg = p.seablue })
hl(0, "TroubleSignHint", { fg = p.teal })
hl(0, "TodoBgFIX", { fg = p.black, bg = p.red, bold = true })
hl(0, "TodoBgHACK", { fg = p.black, bg = p.yellow, bold = true })
hl(0, "TodoBgNOTE", { fg = p.black, bg = p.cyan, bold = true })
hl(0, "TodoBgPERF", { fg = p.black, bg = p.purple, bold = true })
hl(0, "TodoBgTODO", { fg = p.black, bg = p.green, bold = true })
hl(0, "TodoBgWARN", { fg = p.black, bg = p.orange, bold = true })
hl(0, "TodoFgFIX", { fg = p.red })
hl(0, "TodoFgHACK", { fg = p.yellow })
hl(0, "TodoFgNOTE", { fg = p.cyan })
hl(0, "TodoFgPERF", { fg = p.purple })
hl(0, "TodoFgTODO", { fg = p.green })
hl(0, "TodoFgWARN", { fg = p.orange })
hl(0, "TodoSignFIX", { fg = p.red, bg = p.black })
hl(0, "TodoSignHACK", { fg = p.yellow, bg = p.black })
hl(0, "TodoSignNOTE", { fg = p.cyan, bg = p.black })
hl(0, "TodoSignPERF", { fg = p.purple, bg = p.black })
hl(0, "TodoSignTODO", { fg = p.green, bg = p.black })
hl(0, "TodoSignWARN", { fg = p.orange, bg = p.black })
hl(0, "LeapMatch", { fg = p.vibrant_green, bold = true, underline = true })
hl(0, "LeapLabel", { fg = p.black, bg = p.vibrant_green, bold = true })
hl(0, "LeapBackdrop", { fg = p.grey })
hl(0, "FlashBackdrop", { fg = p.grey })
hl(0, "FlashLabel", { fg = p.black, bg = p.pink, bold = true })
hl(0, "FlashMatch", { fg = p.cyan, bold = true })
hl(0, "FlashCurrent", { fg = p.orange, bold = true })
hl(0, "MiniCompletionActiveParameter", { underline = true })
hl(0, "MiniCursorword", { underline = true })
hl(0, "MiniCursorwordCurrent", { underline = true })
hl(0, "MiniIndentscopeSymbol", { fg = p.purple })
hl(0, "MiniIndentscopePrefix", { nocombine = true })
hl(0, "MiniJump", { fg = p.black, bg = p.pink, bold = true })
hl(0, "MiniJump2dSpot", { fg = p.black, bg = p.yellow, bold = true })
hl(0, "MiniStarterCurrent", { nocombine = true })
hl(0, "MiniStarterFooter", { fg = p.grey_fg2, italic = true })
hl(0, "MiniStarterHeader", { fg = p.purple, bold = true })
hl(0, "MiniStarterInactive", { fg = p.grey_fg2, italic = true })
hl(0, "MiniStarterItem", { fg = p.white })
hl(0, "MiniStarterItemBullet", { fg = p.grey })
hl(0, "MiniStarterItemPrefix", { fg = p.yellow })
hl(0, "MiniStarterSection", { fg = p.cyan, bold = true })
hl(0, "MiniStarterQuery", { fg = p.green })
hl(0, "MiniStatuslineDevinfo", { fg = p.white, bg = p.one_bg3 })
hl(0, "MiniStatuslineFileinfo", { fg = p.white, bg = p.one_bg3 })
hl(0, "MiniStatuslineFilename", { fg = p.white, bg = p.one_bg })
hl(0, "MiniStatuslineInactive", { fg = p.grey, bg = p.black })
hl(0, "MiniStatuslineModeCommand", { fg = p.black, bg = p.yellow, bold = true })
hl(0, "MiniStatuslineModeInsert", { fg = p.black, bg = p.blue, bold = true })
hl(0, "MiniStatuslineModeNormal", { fg = p.black, bg = p.purple, bold = true })
hl(0, "MiniStatuslineModeOther", { fg = p.black, bg = p.cyan, bold = true })
hl(0, "MiniStatuslineModeReplace", { fg = p.black, bg = p.red, bold = true })
hl(0, "MiniStatuslineModeVisual", { fg = p.black, bg = p.green, bold = true })
hl(0, "MiniSurround", { fg = p.black, bg = p.orange })
hl(0, "MiniTablineCurrent", { fg = p.white, bg = p.one_bg, bold = true })
hl(0, "MiniTablineFill", { bg = p.black })
hl(0, "MiniTablineHidden", { fg = p.grey, bg = p.black })
hl(0, "MiniTablineModifiedCurrent", { fg = p.yellow, bg = p.one_bg })
hl(0, "MiniTablineModifiedHidden", { fg = p.yellow, bg = p.black })
hl(0, "MiniTablineModifiedVisible", { fg = p.yellow, bg = p.black })
hl(0, "MiniTablineTabpagesection", { fg = p.black, bg = p.purple, bold = true })
hl(0, "MiniTablineVisible", { fg = p.light_grey, bg = p.black })
hl(0, "MiniTestEmphasis", { bold = true })
hl(0, "MiniTestFail", { fg = p.red, bold = true })
hl(0, "MiniTestPass", { fg = p.green, bold = true })
hl(0, "MiniTrailspace", { bg = p.red })
hl(0, "NavicIconsFile", { fg = p.blue })
hl(0, "NavicIconsModule", { fg = p.yellow })
hl(0, "NavicIconsNamespace", { fg = p.yellow })
hl(0, "NavicIconsPackage", { fg = p.yellow })
hl(0, "NavicIconsClass", { fg = p.yellow })
hl(0, "NavicIconsMethod", { fg = p.blue })
hl(0, "NavicIconsProperty", { fg = p.cyan })
hl(0, "NavicIconsField", { fg = p.cyan })
hl(0, "NavicIconsConstructor", { fg = p.yellow })
hl(0, "NavicIconsEnum", { fg = p.yellow })
hl(0, "NavicIconsInterface", { fg = p.yellow })
hl(0, "NavicIconsFunction", { fg = p.blue })
hl(0, "NavicIconsVariable", { fg = p.white })
hl(0, "NavicIconsConstant", { fg = p.orange })
hl(0, "NavicIconsString", { fg = p.green })
hl(0, "NavicIconsNumber", { fg = p.orange })
hl(0, "NavicIconsBoolean", { fg = p.orange })
hl(0, "NavicIconsArray", { fg = p.orange })
hl(0, "NavicIconsObject", { fg = p.yellow })
hl(0, "NavicIconsKey", { fg = p.cyan })
hl(0, "NavicIconsNull", { fg = p.orange })
hl(0, "NavicIconsEnumMember", { fg = p.orange })
hl(0, "NavicIconsStruct", { fg = p.yellow })
hl(0, "NavicIconsEvent", { fg = p.purple })
hl(0, "NavicIconsOperator", { fg = p.cyan })
hl(0, "NavicIconsTypeParameter", { fg = p.yellow })
hl(0, "NavicText", { fg = p.white })
hl(0, "NavicSeparator", { fg = p.grey_fg2 })
hl(0, "DapBreakpoint", { fg = p.red })
hl(0, "DapBreakpointCondition", { fg = p.yellow })
hl(0, "DapBreakpointRejected", { fg = p.grey_fg2 })
hl(0, "DapLogPoint", { fg = p.cyan })
hl(0, "DapStopped", { fg = p.green })
hl(0, "DapUIVariable", { fg = p.white })
hl(0, "DapUIScope", { fg = p.cyan })
hl(0, "DapUIType", { fg = p.yellow })
hl(0, "DapUIValue", { fg = p.white })
hl(0, "DapUIModifiedValue", { fg = p.orange, bold = true })
hl(0, "DapUIDecoration", { fg = p.cyan })
hl(0, "DapUIThread", { fg = p.green })
hl(0, "DapUIStoppedThread", { fg = p.cyan })
hl(0, "DapUIFrameName", { fg = p.white })
hl(0, "DapUISource", { fg = p.purple })
hl(0, "DapUILineNumber", { fg = p.cyan })
hl(0, "DapUIFloatBorder", { fg = p.purple, bg = p.one_bg })
hl(0, "DapUIWatchesEmpty", { fg = p.red })
hl(0, "DapUIWatchesValue", { fg = p.green })
hl(0, "DapUIWatchesError", { fg = p.red })
hl(0, "DapUIBreakpointsPath", { fg = p.cyan })
hl(0, "DapUIBreakpointsInfo", { fg = p.green })
hl(0, "DapUIBreakpointsCurrentLine", { fg = p.green, bold = true })
hl(0, "DapUIBreakpointsLine", { link = "DapUILineNumber" })
hl(0, "DapUIBreakpointsDisabledLine", { fg = p.grey_fg2 })
hl(0, "DapUICurrentFrameName", { link = "DapUIBreakpointsCurrentLine" })
hl(0, "DapUIStepOver", { fg = p.cyan })
hl(0, "DapUIStepInto", { fg = p.cyan })
hl(0, "DapUIStepBack", { fg = p.cyan })
hl(0, "DapUIStepOut", { fg = p.cyan })
hl(0, "DapUIStop", { fg = p.red })
hl(0, "DapUIPlayPause", { fg = p.green })
hl(0, "DapUIRestart", { fg = p.green })
hl(0, "DapUIUnavailable", { fg = p.grey_fg2 })
hl(0, "NeotestAdapterName", { fg = p.purple, bold = true })
hl(0, "NeotestBorder", { fg = p.purple })
hl(0, "NeotestDir", { fg = p.cyan })
hl(0, "NeotestExpandMarker", { fg = p.grey_fg2 })
hl(0, "NeotestFailed", { fg = p.red })
hl(0, "NeotestFile", { fg = p.cyan })
hl(0, "NeotestFocused", { bold = true })
hl(0, "NeotestIndent", { fg = p.grey })
hl(0, "NeotestMarked", { fg = p.orange, bold = true })
hl(0, "NeotestNamespace", { fg = p.blue })
hl(0, "NeotestPassed", { fg = p.green })
hl(0, "NeotestRunning", { fg = p.yellow })
hl(0, "NeotestSkipped", { fg = p.cyan })
hl(0, "NeotestTarget", { fg = p.purple })
hl(0, "NeotestTest", { fg = p.white })
hl(0, "NeotestWinSelect", { fg = p.cyan, bold = true })
hl(0, "NeotestUnknown", { fg = p.grey_fg2 })
hl(0, "NeotestWatching", { fg = p.yellow })
hl(0, "NeogitBranch", { fg = p.purple })
hl(0, "NeogitRemote", { fg = p.pink })
hl(0, "NeogitHunkHeader", { fg = p.white, bg = p.one_bg3 })
hl(0, "NeogitHunkHeaderHighlight", { fg = p.cyan, bg = p.one_bg3 })
hl(0, "NeogitDiffContextHighlight", { bg = p.one_bg })
hl(0, "NeogitDiffDeleteHighlight", { fg = p.red, bg = p.one_bg })
hl(0, "NeogitDiffAddHighlight", { fg = p.green, bg = p.one_bg })
hl(0, "NeogitNotificationInfo", { fg = p.seablue })
hl(0, "NeogitNotificationWarning", { fg = p.yellow })
hl(0, "NeogitNotificationError", { fg = p.red })
hl(0, "NeogitChangeModified", { fg = p.yellow })
hl(0, "NeogitChangeAdded", { fg = p.green })
hl(0, "NeogitChangeDeleted", { fg = p.red })
hl(0, "NeogitChangeRenamed", { fg = p.purple })
hl(0, "NeogitChangeUpdated", { fg = p.orange })
hl(0, "NeogitChangeCopied", { fg = p.cyan })
hl(0, "NeogitChangeUnmerged", { fg = p.orange })
hl(0, "NeogitChangeNewFile", { fg = p.green })
hl(0, "SymbolsOutlineConnector", { fg = p.grey })
hl(0, "FocusedSymbol", { bg = p.one_bg3 })
hl(0, "LightBulbSign", { fg = p.yellow })
hl(0, "LightBulbFloatWin", { fg = p.yellow, bg = p.one_bg })
hl(0, "LightBulbVirtualText", { fg = p.yellow })
hl(0, "OverseerPENDING", { fg = p.yellow })
hl(0, "OverseerRUNNING", { fg = p.blue })
hl(0, "OverseerSUCCESS", { fg = p.green })
hl(0, "OverseerCANCELED", { fg = p.grey_fg2 })
hl(0, "OverseerFAILURE", { fg = p.red })
hl(0, "OverseerTask", { fg = p.white })
hl(0, "OverseerTaskBorder", { fg = p.purple, bg = p.one_bg })
hl(0, "OverseerOutput", { fg = p.white })
hl(0, "OverseerComponent", { fg = p.cyan })
hl(0, "OverseerField", { fg = p.cyan })
hl(0, "HarpoonBorder", { fg = p.purple, bg = p.one_bg })
hl(0, "HarpoonWindow", { bg = p.one_bg })
hl(0, "FidgetTask", { fg = p.grey_fg2 })
hl(0, "FidgetTitle", { fg = p.purple, bold = true })
hl(0, "barbecue_separator", { fg = p.grey_fg2 })
hl(0, "barbecue_dirname", { fg = p.grey_fg2 })
hl(0, "barbecue_basename", { fg = p.white, bold = true })
hl(0, "barbecue_context", { fg = p.white })
hl(0, "barbecue_context_file", { fg = p.blue })
hl(0, "barbecue_context_module", { fg = p.yellow })
hl(0, "barbecue_context_namespace", { fg = p.yellow })
hl(0, "barbecue_context_package", { fg = p.yellow })
hl(0, "barbecue_context_class", { fg = p.yellow })
hl(0, "barbecue_context_method", { fg = p.blue })
hl(0, "barbecue_context_property", { fg = p.cyan })
hl(0, "barbecue_context_field", { fg = p.cyan })
hl(0, "barbecue_context_constructor", { fg = p.yellow })
hl(0, "barbecue_context_enum", { fg = p.yellow })
hl(0, "barbecue_context_interface", { fg = p.yellow })
hl(0, "barbecue_context_function", { fg = p.blue })
hl(0, "barbecue_context_variable", { fg = p.white })
hl(0, "barbecue_context_constant", { fg = p.orange })
hl(0, "barbecue_context_string", { fg = p.green })
hl(0, "barbecue_context_number", { fg = p.orange })
hl(0, "barbecue_context_boolean", { fg = p.orange })
hl(0, "barbecue_context_array", { fg = p.orange })
hl(0, "barbecue_context_object", { fg = p.yellow })
hl(0, "barbecue_context_key", { fg = p.cyan })
hl(0, "barbecue_context_null", { fg = p.orange })
hl(0, "barbecue_context_enum_member", { fg = p.orange })
hl(0, "barbecue_context_struct", { fg = p.yellow })
hl(0, "barbecue_context_event", { fg = p.purple })
hl(0, "barbecue_context_operator", { fg = p.cyan })
hl(0, "barbecue_context_type_parameter", { fg = p.yellow })

-- =============================================================================
-- 5. INTEGRATIONS & ADDITIONAL PLUGINS
-- =============================================================================

hl(0, "IlluminatedWordText", { bg = p.one_bg3 })
hl(0, "IlluminatedWordRead", { bg = p.one_bg3 })
hl(0, "IlluminatedWordWrite", { bg = p.one_bg3 })
hl(0, "RainbowDelimiterRed", { fg = p.red })
hl(0, "RainbowDelimiterYellow", { fg = p.yellow })
hl(0, "RainbowDelimiterBlue", { fg = p.blue })
hl(0, "RainbowDelimiterOrange", { fg = p.orange })
hl(0, "RainbowDelimiterGreen", { fg = p.green })
hl(0, "RainbowDelimiterViolet", { fg = p.purple })
hl(0, "RainbowDelimiterCyan", { fg = p.cyan })
hl(0, "YankyPut", { link = "IncSearch" })
hl(0, "YankyYanked", { link = "IncSearch" })
hl(0, "Hlargs", { fg = p.sun })


